pupil-labs/pupil

pupil_src/player/seek_bar.py
Hi, I'm using pupil-pro in my lab. It really helps me.
I'm using pupil on MacBook Pro with retina display. But it seems that the seeking bar of pupil-player doesn't work on retina display. So I did some fixation on `SeekBar` class.
I'm new to contributing to open-source projects, so feel free to give feedback on my pull request process :)
=> Enabled seeking bar on retina displays

pupil_src/shared_modules/offline_reference_surface.py
when `section.start > 0`, frame_idx (L257) does not reflect the frame index producing buggy heatmaps;
The `gaze_on_srf_in_section` method is already using `frame_idx+=section.start`, so I just copy and paste it.
=> fix slice((start > 0), stop, step) heatmap bug

pupil_src/shared_modules/offline_marker_detector.py
Moving surface initialization code to a separated method. I am having some problems trying to override the __init__ directly with multiple inheritance. This should make it easier to do it.
=> allow easy to override surface initialization

pupil_src/shared_modules/calibration_routines/accuracy_test.py, pupil_src/shared_modules/calibration_routines/adjust_calibration.py, pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/circle_detector.py
This PR improves the circle marker detector we use for calibration:
- The detector now analyses the contour hierarchy to find clusters of nested contours.
- The detected clusters are filtered for ellipse contour fit. 
- The detected clusters are filtered against eccentricity.
With these changes the detector is more discriminative and allows us to use smaller and simpler markers like the one below:
The simple marker above printed with a diameter of 40mm can be used at distances of 2m with current Pupil hardware. The old marker is still supported and will continue working.
=> Improve circle marker detector

pupil_src/capture/recorder.py, pupil_src/capture/world.py, pupil_src/shared_modules/video_capture/uvc_capture.py
The PR improves capture robustness and failed capture feedback.
- The pupil video_backend now tries to restart the capture device after all attempts to read from the device have failed.
- The world process with fall back to a `fake capture` if all attempts to restart and recover communications with the camera have failed. This behaviour is better feedback to the user than a shutdown of the capture program.
- The world process will stop recording when the fallback to `fake capture` happens.
This PR requires an updated of [pyuvc](https://github.com/pupil-labs/pyuvc) to v0.6
=> Capture robustification

pupil_src/capture/world.py, pupil_src/shared_modules/pupil_remote.py
This PR adds  `Pupil Remote`" 
- Motivated by #352 and conversations with pupil community members ( @papr , @cpicanco  and others ).
- A new plugin that offers a simple way of controlling pupil from non python environments like matlab 
- It handles requests in a separate thread to reduce latency. (As opposed to the initial version posted in  #352)
=> Pupil remote

pupil_src/capture/world.py, pupil_src/player/main.py, pupil_src/shared_modules/log_history.py
Proposing `log_history` plugin for Pupil Capture motivated by UX testing feedback from @nathakits, @DouglasMackay and conversations with other members in the Pupil community about the brevity of the log messages.
This is a simple (convenience) plugin that shows the last 50 log messages as `Info_Text` within a separate GUI window (`Scrolling_Menu`). The most recent log message appears at the top. This plugin is motivated by feedback from UX tests and provides a way to review log messages in the case that they were not seen when they were rendered by `Log_Display`. Full logs are written to files, so this just provides a glimpse into the past instead of a full record.
Other enhancements to this plugin could include a timestamp for the log messages so that log messages are prepended with the …
=> Log History - GUI window that displays last 50 logger messages

pupil_src/capture/eye.py, pupil_src/capture/main.py, pupil_src/capture/world.py, pupil_src/shared_modules/log_display.py, pupil_src/shared_modules/video_capture/uvc_capture.py
This PR improves the logging experience:
- It gives all processes a name so the logging record processName attribute become meaningful to the user.
- It uses a custom handler in the eye process to send pickled log records to the world process via ZMQ PUB/SUB on `tcp://127.0.0.1:502020`
- It adds a log collection thread in the world process that received the eye log records and handles them accordingly.
- All logs now show up in the world process.
- All logs are now written to `capture.log` instead of `world/eye/0/1.log`.
=> Ipc logging

pupil_src/shared_modules/plugin.py, pupil_src/shared_modules/pupil_remote.py, pupil_src/shared_modules/pupil_server.py, pupil_src/shared_modules/zmq_tools.py
Use `zmq_tools.serializer.dumps()` to encode and `.loads()` to decode messages. `zmq_tools.py` will be the central place to configure the serialization method.
@mkassner Please review.
=> Switch from `json` to `msgpack` message serialisation

pupil_src/capture/service.py, pupil_src/capture/world.py, pupil_src/shared_modules/pupil_groups.py
- Creates `Pyre` node with following headers:
- "pub_address"
- "sub_address"
- "app_type"
- Joins "pupil-groups” group by default.
- Uses `remote_notify` functionality introduced in a652f81baf83. If the mapped value of the notification key `remote_notify` is equal to "all" the notification will be SHOUTed. Else it will use the value as peer uuid and try to WHISPER the notification to the respective peer.
- Publishes all discovered notifications to the IPC backbone
- Drops notifications which cannot be unpacked with msgpack
or do not have "subject" key
- Adds "discovery.peer" key with dictionary containing information:
- "uuid": peer uuid
- "name": peer name
- "arrival_timestamp": time of arrival
- "type: "SHOUT" or "WHISPER"
=> `Pupil_Groups` Implementation (Clean history)

pupil_src/capture/pupil_detectors/setup.py, pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py
Hi,
This is (re-)introducing the ability to use OpenCV3 provided by ROS. This is only used if OpenCV3 is not found in the default path. I've extended it a little so is searches through all ROS distributions which provide OpenCV3. It will also be easy to extend this for other operating systems etc.
Best,
Tobias
=> Fixes for OpenCV3 using ROS

pupil_src/shared_modules/video_capture/fake_backend.py
Don't use range(30,60,90,120) to return frame rates.
Instead just return as a list (30,60,90,120)
Error without fix on startup:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/pupil/pupil/pupil_src/capture/world.py", line 216, in world
>     cap = Fake_Source(g_pool, **settings)
>   File "/home/pupil/pupil/pupil_src/shared_modules/video_capture/fake_backend.py", line 76, in __init__
>     self.settings = settings
>   File "/home/pupil/pupil/pupil_src/shared_modules/video_capture/fake_backend.py", line 143, in settings
>     self.frame_rate = …
=> Fix backend script

pupil_src/shared_modules/fixation_detector.py
Problem: If the newer timestamp would be smaller than the old one the fixation detector would not free data and distance calculation would slow down everything over time.
=> Fix negative time difference in fixation detector 

pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py
To upgrade calibration settings file, load the file content, change the keys to unicode objects, store it back to the file.
=> Fixes deprecated camera calibration format #639

pupil_src/shared_modules/audio/__init__.py
Fixes #651
platform.linux_distribution() returns different values when running from bundle
=> Fix broken Audio Modes in Capture 0.9.1 linux bundle

pupil_src/shared_modules/calibration_routines/gaze_mappers.py
min/maxing to in an integer value caused an integer to be returned in the edge case, instead of the wanted float
=> FIX issue #598

pupil_src/capture/eye.py, pupil_src/capture/world.py, pupil_src/player/main.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/log_display.py
`glfw` differentiates between _frame buffer size_ and _window size_ -- the former referring to the size in pixels and the lather to the size in screen coordinates (see [docs](http://www.glfw.org/docs/latest/group__window.html#ga0e2637a4161afb283f5300c7f94785c9)). Usually, these sizes are the same but they differ on screens with higher pixel densities (e.g. Retina displays).
This can lead to unexpected behavior of the ui. This pull request reacts appropriately to changes in pixel densities and fixes unexpected behavior.
Requires `pyglui` `v1.3` or higher (https://github.com/pupil-labs/pyglui/pull/45)
=> Consistent ui scaling across different monitor pixel densities

pupil_src/shared_modules/time_sync.py, pupil_src/shared_modules/video_capture/uvc_backend.py
Pyre does not have .version() implemented before 0.3.2,
therefore the relatively complex version test.
+ small typo fixes
=> Add version requirement for pyre >= 0.3.1

pupil_src/shared_modules/video_capture/ndsi_backend.py
To be merged when Pupil Mobile has implemented Time Sync.
=> Require pyndsi version 0.3.0 and higher

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/calibration_routines/single_marker_calibration.py, pupil_src/shared_modules/calibration_routines/visualizer_calibration.py, pupil_src/shared_modules/plugin.py, pupil_src/shared_modules/pupil_detectors/Tests/SphereCircleTests/VisualizeSphere.py, pupil_src/shared_modules/pupil_detectors/detector_2d.pyx, pupil_src/shared_modules/pupil_detectors/visualizer_3d.py, pupil_src/shared_modules/reference_surface.py, pupil_src/shared_modules/visualizer.py
Requires pyglui >=1.6
This is the possibility for plugins to access unconsumed* GLFW events without having to overwrite the GLFW callbacks, as requested internally.
\* "unconsumed" means that there was no gui element that used the event for itself, e.g. no `Text_Input` used the char as input.
=> Add on_unconsumed_key/char events

pupil_src/launchables/world.py, pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/display_recent_gaze.py, pupil_src/shared_modules/fixation_detector.py
=> Unify online fixation detectors

pupil_src/shared_modules/blink_detection.py, pupil_src/shared_modules/video_capture/realsense_backend.py
- Fix RealSense backend: Always initialize `self.streams`
- Blink detector: Enable recording of events
=> Fixes for RealSense backend and blink detection

pupil_src/shared_modules/pupil_producers.py, pupil_src/shared_modules/video_capture/fake_backend.py, pupil_src/shared_modules/video_capture/file_backend.py, pupil_src/shared_modules/video_capture/ndsi_backend.py, pupil_src/shared_modules/video_capture/realsense_backend.py
1. Fixes #813
2. Make sure `source.intrinsics` is not `None`
=> Accept mkv eye videos in Offline Pupil Detection and set dummy camera models

pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py, pupil_src/shared_modules/circle_detector.py
[The 1-ring-marker](
https://docs.pupil-labs.com/images/pupil-capture/calibration-markers/pupil_calibration_marker.v0914.pdf) and [the 2-rings-marker](
https://drive.google.com/open?id=0BzhCo4DVViZKeFl0dENVYjd1eUE) are used as standard markers.
=> To improve the accuracy of correct marker detection in manual marker calibration

pupil_src/shared_modules/video_capture/realsense_backend.py
Restrict available frame rate settings according to RS device limitation:
Color frame rate should divide depth frame rate
=> Add stream preset settings to Realsense backend

pupil_src/shared_modules/offline_surface_tracker.py, pupil_src/shared_modules/vis_eye_video_overlay.py
Problem: With the introduction of the icon bar the camera image is not visualized in the whole window anymore but in a smaller area. Mouse positions need to be normalized in relation to this smaller area (`g_pool.camera_render_size`) instead of the window size.
Two plugins have been affected by this change and have been behaving incorrectly on user mouse input:
1. `Vis Eye Video Overlay`
2. `Offline Surface Tracker`
=> Fix mouse position normalization

pupil_src/shared_modules/av_writer.py
The transcoding thread count was previously set to one. This was due to a bug on Linux where the program would crash if more threads than available cpus were used.
=> Use as many threads to transcode video as there are cpus

pupil_src/launchables/eye.py, pupil_src/shared_modules/pupil_producers.py
Fixes the visualization of the pupil ellipses in the eye overlay plugin and calculates the offline pupil detection progress based on how many detection processes are active.
- #891
- #892
~~Concerning b7d766e:
This implementation uses the number of currently running detection processes to calculate the total progress. This leads to a short jump in the progress indicator as soon as one detection process finishes before the other. Is this an acceptable behavior? The alternative would be a slightly more complex implementation. Shot screen capture:
=> Offline Pupil Detector Fixes

pupil_src/shared_modules/reference_surface.py
Fixing the spelling of `correspondence` and a small typo in code comments.
=> Typo Fix spelling of 'correspondence'

pupil_src/shared_modules/fixation_detector.py
The fixation detector does not detect a high amount of fixations if `max_duration` is set to an high value.
The fixation detector detects fixations of maximal length given a specific window. This window was not reset correctly after finding a fixation.
Reset detection window correctly and increase window only if necessary.
=> Decrease false negatives in fixation detector

pupil_src/shared_modules/batch_exporter.py, pupil_src/shared_modules/exporter.py
This PR fixes an issue where the batch export would not export videos due to an invalid argument.
Support for recordings with data format `<v0.4` has been removed as well in 60df7c5. This brings up the question if the (batch) exporter should be responsible for upgrading recordings. ~~We will add an assertion for now that test if the recording is up-to-date.~~ We will add `player_methods.update_recording_to_recent()` to the start of the video export process.
=> Fix invalid batch exporter argument

pupil_src/shared_modules/vis_scan_path.py
Problem: Scan Path does not propergate changed gaze positions correctly. This led to visualization plugins displaying incorrect gaze when the playback was paused and the e.g. the manual gaze correction was applied.
=> Scan Path: Update gaze positions on change

pupil_src/shared_modules/calibration_routines/hmd_calibration.py, pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py, pupil_src/shared_modules/calibration_routines/natural_features_calibration.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/calibration_routines/single_marker_calibration.py
Solution: A running calibration needs to be stopped before the UI is being deinitialized.
=> Fix crash when changing calibration method during calibration

pupil_src/launchables/player.py, pupil_src/shared_modules/background_helper.py, pupil_src/shared_modules/batch_exporter.py, pupil_src/shared_modules/exporter.py, pupil_src/shared_modules/video_export_launcher.py
This PR uses #927 to fix #913.
The batch export is split into 4 stages:
1. Search for available recordings
2. Queued exports
3. Active exports
4. Previous exports
- Canceling a queued export (2) puts it back to the list of available recordings (1).
- Canceling an active export (3) adds the export to the list of previous exports (4).
I feel like (1) and (2-4) should be split into two different menus. What do you think about that?
=> Refactor Batch Exporter

pupil_src/shared_modules/calibration_routines/gaze_mappers.py, pupil_src/shared_modules/calibration_routines/hmd_calibration.py
The back projection of the 3d gaze point onto the world frame does
not make sense for the 3d HMD calibration. Therfore we decided to
make the backprojection an opt-out feature.
=> Binocular Vector Gaze Mapper: Opt-out option for gaze backprojection

pupil_src/launchables/world.py, pupil_src/shared_modules/calibration_routines/gaze_mappers.py, pupil_src/shared_modules/hololens_relay.py, pupil_src/shared_modules/udp_backend.py
Description is taken from the plugin's doc string:
This plugins defines a very narrow api that is custimized to work with the Pupil-Hololens-integration. On startup a udp socket is opened that can be changed in the user settings.
The Hololens side will be called the `client` and the plugin the `server`.
Communication is initialized by the client. The server determines the address of the client by calling `recvfrom()`. All server respones are sent to the most recent client address. This means that the client needs to listen on the same socket that it uses to send requests.
All messages start with an ascii-encoded header byte. Server acknowledgments start either with ascii `0` on success or `F` on failure, followed by the request's header byte. In some cases, there are further bytes …
=> Hololens Relay

pupil_src/shared_modules/pupil_detectors/singleeyefitter/solve.h
Fixes #975. I would like to know if this fix has an impact on the model fitter and if this might ave been the cause for instable models...
=> Singleeyefitter: Fix type where solve() returned a wrong variable

pupil_src/shared_modules/video_capture/ndsi_backend.py
ndsi v0.3.3 includes the bug fixes for #976 and #910 
*This PR requires https://github.com/pupil-labs/pyndsi/pull/31 to be merged first.*
=> Require ndsi >= v0.3.3

pupil_src/launchables/eye.py, pupil_src/launchables/world.py, pupil_src/main.py, pupil_src/shared_modules/pupil_detectors/__init__.py, pupil_src/shared_modules/pupil_detectors/detector_dummy.py
Feature idea by @anligert. Online pupil detection is not required if one plans to use offline pupil detection anyway. Select `disable` as `detection & mapping mode` in the general settings to turn off pupil detection and gaze mapping. Do not forget to enable the `Record eye` option in the recorder settings if you do not use online pupil detection.
=> Opt-out online pupil detection

pupil_src/launchables/player.py, pupil_src/launchables/world.py
The idea is to collapse the main menu by default. We were not able to do so before the introduction of the icon bar since the collapse icon was not obvious to the user. It is more obvious that the icons allow interaction. Having the menu collapsed initially shows the user that the main menu can be collapsed. This is important for those users that used to drag the menu to collapse it. This is not possible anymore with the introduction of the minimum menu width.
=> Capture/Player: Collapsed main menu by default

pupil_src/shared_modules/recorder.py
The unix timestamp corresponds to the Python system timebase, the synced timestamp corresponds to the synced timebased used for all data points in the recording.
Fixes #989, #982
=> Recorder: Add unix and synced recording start times to info.csv

pupil_src/launchables/service.py, pupil_src/launchables/world.py, pupil_src/shared_modules/plugin.py, pupil_src/shared_modules/service_ui.py
The only way to quit `Service` is via notifications, since it does not have a main window. This PR adds a small main window to the `Service` process that allows the user to:
- Start/stop eye processes
- Reset the user settings
- Set the detection and mapping method
- Quit `Service` by closing the main window
=> Service UI settings

pupil_src/launchables/player.py, pupil_src/shared_modules/gaze_producers.py
~Also sets the calibration default ranges to `00:00 - 00:00`. This is intentionally set to this range to encourage the user to set sensible calibration and mapping ranges.~
Fixes #996, requires [`pyglui >=v1.17`](https://github.com/pupil-labs/pyglui/pull/96)
=> Offline Calibration: Trim calibration and mapping ranges using trim marks

pupil_src/shared_modules/pupil_producers.py, pupil_src/shared_modules/system_timelines.py
Previously, the timelines would recalculate these data points on each draw command. The new implementation calculates and caches the data points only if they change.
=> Player timelines: Cache drawn fps and pupil data

pupil_src/launchables/marker_detectors.py, pupil_src/launchables/player.py, pupil_src/shared_modules/background_helper.py, pupil_src/shared_modules/exporter.py, pupil_src/shared_modules/gaze_producers.py, pupil_src/shared_modules/marker_detector_cacher.py, pupil_src/shared_modules/offline_surface_tracker.py, pupil_src/shared_modules/player_methods.py, pupil_src/shared_modules/seek_control.py, pupil_src/shared_modules/video_capture/__init__.py, pupil_src/shared_modules/video_capture/base_backend.py, pupil_src/shared_modules/video_capture/fake_backend.py, pupil_src/shared_modules/video_capture/file_backend.py, pupil_src/shared_modules/vis_eye_video_overlay.py
Creates an artificial video source in case that no world video was encountered. Timestamps will be generated based on encountered eye video timestamps.
=> Support Pupil Mobile recordings without world video

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/calibration_routines/single_marker_calibration.py, pupil_src/shared_modules/glfw.py, pupil_src/shared_modules/log_display.py, pupil_src/shared_modules/service_ui.py, pupil_src/shared_modules/system_graphs.py, pupil_src/shared_modules/vis_eye_video_overlay.py, pupil_src/shared_modules/visualizer.py
Reasoning: `glfwGetWindowSize` might return window widths of value `zero` on Windows.
Fixes #1087
=> Avoid ZeroDivisionError when calculating hdpi factors

pupil_src/launchables/player.py, pupil_src/shared_modules/file_methods.py, pupil_src/shared_modules/raw_data_exporter.py, pupil_src/shared_modules/seek_control.py, pupil_src/shared_modules/video_export_launcher.py
- Add trim section displays to general settings
- Relative recording time
- Frame indeces
- Remove trim section displays from video and raw data exporters
- Add export_info.csv
- Player version
- Data format version
- Export start date and time
- Frame index trim range
- Relative time trim range
- Absolute time trim range (`world` timestamp range)
- Do not use trim range as naming convention
- Use incrementally increasing folder names with format `%d%d%d`, e.g.:
- `<recording>/exports/000/`
- `<recording>/exports/001/`
- `<recording>/exports/002/`
=> Player: Incremental increasing export folder names

pupil_src/launchables/player.py, pupil_src/launchables/service.py, pupil_src/launchables/world.py, pupil_src/shared_modules/calibration_routines/calibration_plugin_base.py, pupil_src/shared_modules/calibration_routines/finish_calibration.py, pupil_src/shared_modules/calibration_routines/gaze_mappers.py, pupil_src/shared_modules/calibration_routines/hmd_calibration.py, pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py, pupil_src/shared_modules/calibration_routines/natural_features_calibration.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/calibration_routines/single_marker_calibration.py, pupil_src/shared_modules/gaze_producers.py
1. Previously, all binocular mappers dismissed pupil data with confidence lower than `0.6` to prevent bad binocular mapping. Now, low confidence pupil data is mapped monocularly.
2. Introduction of a user-settable global **minimum calibration confidence** threshold: A threshold that lower bounds the pupil data confidence that is used for calibration. This value was previously fixed to `0.8` in Pupil Capture and to `0.0` in Pupil Player -- effectively using low confidence pupil data for calibration.
These changes were introduced based on #1052 and #1047.
**Minimum data confidence**: Lower bounds _gaze_ data by confidence that is used to generate visualizations and high level data, e.g. fixations. This does not effect the raw data export. Following data points are effected by it:
- …
=> Confidence threshold consistency

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/calibration_routines/single_marker_calibration.py, pupil_src/shared_modules/reference_surface.py, pupil_src/shared_modules/service_ui.py, pupil_src/shared_modules/visualizer.py
If a user sets the system taskbar to be located at the top of their screen, application window controls will be located underneath the taskbar. With old default `y` value for `window_position_default` this would make it impossible for a user to move or close the application window. 
The proposed `y` value in this PR is set to `90`. The default Windows taskbar height is approx `50` pixels in height and the window controls are approx `40` pixels in height. This positions the Pupil application windows just below the taskbar if taskbar is positioned at the top of the screen. 
We might want to consider updating `window_position_default` `x` value to `50` so that none of our application windows will be under the taskbar if the user has set the task bar to be located on the left hand side of the …
=> Set default Y position of application windows to 90 for Windows OS

pupil_src/shared_modules/video_capture/utils.py, pupil_src/shared_modules/video_capture/uvc_backend.py
Check if there are stripes in the frames of the 200 HZ eye camera.
If yes, restart the camera.
Workaround for  #1116
=> Reinit 200Hz eye cameras if stripe effect was detected

.travis.yml, deployment/bundle.sh
Automated bundle builds for Ubuntu 16.04. The `.travis.yml` file instructs travis to create a bundle on each commit to the master branch. If the bundle builds successfully it will be added as a new **draft** release on `pupil-labs/pupil/releases`. 
Note that a successful build does not necessarily mean that it is a working bundle. Human testing of the bundle is still required on a host system with Pupil hardware.   
- Triggers for build - currently a new build is triggered on a commit to master. But, maybe we only want to make a build for each minor tag. @mkassner @papr what do you think? 
The Pupil app bundles are built using our Ubuntu 16.04 Docker image. The Dockerfile for the 16.04 is the master branch of [this repo](https://github.com/pupil-labs/pupil-docker-ubuntu). The docker image …
=> Travis-ci linux bundles

deployment/deploy_capture/bundle.spec, deployment/deploy_player/bundle.spec, deployment/deploy_service/bundle.spec
bundle in docker image will not run unless the path to `libglfw` is correctly specified.
=> update glfw path for docker image's system libglfw

pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py, pupil_src/shared_modules/pupil_detectors/setup.py
With the newest version of `bosst-python3` installed with `brew`, the linker must be changed to include the minor version along the major version (`-lboost_python36` instead of `-lboost_python3`). 
[I think this commit caused the change.](https://github.com/Homebrew/homebrew-core/commit/333a3293ed45c918272e248ef133838b2d7e6c61) At least that's when they changed the flags in the test.
This was only tested with macOS High Sierra and Python 3.6!
=> Fix boost linker flags on macOS

pupil_src/main.py, pupil_src/shared_modules/recorder.py
Fixes issue on Windows with unicode characters that are not present in the system locale
Requires : [Use utf-8 encoding for codec name](https://github.com/pupil-labs/PyAV/pull/11)
=> Force logging and csv encodings to utf-8

pupil_src/shared_modules/fixation_detector.py
Previously, the online fixation detector created a lot of data since it included all gaze data and its corresponding pupil data.
This change replaces the gaze data within the `base_data` field with `(topic, timestamp)` tuples which can be used to identify the original gaze data.
=> Online Fixation Detector: Replace base data with references

pupil_src/shared_modules/audio_playback.py, pupil_src/shared_modules/audio_utils.py, pupil_src/shared_modules/video_capture/file_backend.py
[Python 3.7](https://docs.python.org/3/whatsnew/3.7.html#changes-in-python-behavior) enforces [PEP 479](https://www.python.org/dev/peps/pep-0479/). Raising a `StopIteration` within a generator will raise a RuntimeError instead.
=> PEP 479 incompatibility

pupil_src/shared_modules/video_export_launcher.py
This fixes #1295 
The file path and the file name are displayed once the export is done, so I removed most of the text from the right pane (but left them commented for the moment).
=> Video Export Launcher: Fix filenames 

pupil_src/shared_modules/player_methods.py, pupil_src/shared_modules/pupil_producers.py
Previously, pupil data was loaded into a Bisector pupil_positions that was split to create pupil_positions_by_id. However, during the creation of this Bisector the data gets sorted s.t. the data from the Bisector did not fit with the content of the topics variable.
This fixes this by creating pupil_positions_by_id from the original pupil data instead of the Bisector.
=> Fix pupil_positions_by_id

pupil_src/shared_modules/eye_video_exporter.py, pupil_src/shared_modules/imotions_exporter.py, pupil_src/shared_modules/video_exporter.py
this fixes the first two issues in https://github.com/pupil-labs/pupil/issues/1312
=> Improve Eye Video Export

pupil_src/shared_modules/video_capture/uvc_backend.py
match frame resolution in both dimensions instead of only the first dimension.
=> match frame resolution in both dimensions

pupil_src/shared_modules/remote_recorder.py
"python3 main.py" will not run if the 4 lines are not commented out
What are those lines for?
=> Remote Recorder: Remove type annotations due to Python 3.5 incompatibility

pupil_src/shared_modules/video_export/plugins/eye_video_exporter.py
When starting a background process on Windows, the os creates an actual new process (instead of just a new fork). Therefore, everything needs to be copied / pickled. The eye video exporter formerly used a function factory to create a function that renders pupil positions, but the returned function would not be pickleable. This is now fixed by replacing the old functionality with a callable class that can get copied to the background process.
=> Make add_pupil_ellipse a class to make it picklable

pupil_src/shared_modules/video_capture/uvc_backend.py
`%s` doesn't work, replaced with `{}`.
=> fix typo in uvc_backend for logger

pupil_src/shared_modules/pupil_remote.py, pupil_src/shared_modules/zmq_tools.py
Fixes #1378 
- single-frame zmq messages containing utf-8 encoded text.
- interpreted by Pupil Remote
- zmq messages containing more than one frame
- all frames are forwarded to the IPC
=> Pupil Remote: Forward IPC/multipart messages

pupil_src/launchables/args.py, pupil_src/launchables/service.py, pupil_src/launchables/world.py, pupil_src/main.py, pupil_src/shared_modules/pupil_remote.py, pupil_src/shared_modules/service_ui.py
This PR implements #1315 by fixing #1377 
Todos:
---
```bash
> python main.py -h
usage: main.py [-h] [--debug] [--profile] {capture,service,player} ...
optional arguments:
-h, --help            show this help message and exit
--debug               display debug log messages
--profile             profile the application's CPU time
Applications:
Select which application you want to run, by default `capture`
{capture,service,player}
capture             Real-time processing and recording
service             VR/AR interface
player              Process, visualize, and export recordings
```
```bash
> python main.py capture -h
usage: main.py capture [-h] [-P PORT]
optional arguments:
-h, --help            show this help message and exit
-P PORT, --port PORT  Pupil Remote port
```
```bash
> python …
```
=> Settable Pupil Remote port via argument parsing

pupil_src/launchables/eye.py, pupil_src/shared_modules/pupil_detectors/detector_2d.pyx, pupil_src/shared_modules/pupil_detectors/detector_3d.pyx, pupil_src/shared_modules/pupil_detectors/detector_dummy.py, pupil_src/shared_modules/pupil_detectors/detector_utils.pxd
Fixes #1372
The `Pupil Detector Network API` allows to request the current pupil detector properties as well as setting specific properties via notifications.
See https://github.com/pupil-labs/pupil-helpers/pull/32 for a test/example script.
Note: `target` fields are optional, if not provided all active eye processes will handle the notification
```python
{"subject": "pupil_detector.broadcast_properties", "target": "eye0"}
```
- The response notification keys depend on the active pupil detector:
- `Dummy Detector`: `subject`, `topic`
- `Detector 2D`: `subject`, `topic`, `2d`
- `Detector 3D`: `subject`, `topic`, `2d`, `3d`
- The subject/topic indicate the eye id of the originating process.
Example `pupil_detector.properties.X` output:
```python
{'2d': {'blur_size': 5,
'canny_aperture': 5, …
```
=> Pupil Detector Network API

pupil_src/launchables/player.py, pupil_src/shared_modules/gaze_producer/controller/reference_location_controllers.py, pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py, pupil_src/shared_modules/gaze_producer/model/reference_location.py, pupil_src/shared_modules/gaze_producer/model/reference_location_storage.py, pupil_src/shared_modules/gaze_producer/ui/reference_location_menu.py, pupil_src/shared_modules/gaze_producer/ui/reference_location_renderer.py, pupil_src/shared_modules/gaze_producer/ui/timeline.py, pupil_src/shared_modules/gaze_producer/worker/detect_circle_markers.py, pupil_src/shared_modules/observable.py, pupil_src/shared_modules/plugin_timeline.py, pupil_src/shared_modules/tasklib/interface.py
Main functionality for new gaze producer plugins:
- Detect circle markers and use them as reference locations
- Manual edit mode
- Jump to next / previous reference
- Timeline showing reference locations and progress of detection
New general functionality:
- `PluginTimeline`: Simple timeline to separate the `pyglui` stuff from the content of a timeline.
Additionally:
- `Observable`: Fix a little issue that `ObserverErrors` get wrapped into each other (and thus cluttering the traceback) when observers trigger more observers.
- `tasklib`: Expand with new event `on_started`
=> Reference Location Management

pupil_src/shared_modules/raw_data_exporter.py
Fixes regression from 8119d620b4d153de37479fa021029b8671b87106
The `timestamp` column in `pupil_positions.csv` and `gaze_positions.csv` do not refer to world frame timestamps but to pupil and gaze timestamps (inferred from eye frame timestamps) respectively.
=> Raw Data Exporter: Clarify timestamp column names

pupil_src/shared_modules/calibration_routines/fingertip_calibration/models/unet.py
pytorch 1.0 shows a deprecation warning for `torch.nn.functional.tanh()`
@ChingT please review as well.
=> unet: Replace `torch.nn.functional` functions with their respective `torch` counterparts

pupil_src/shared_modules/background_helper.py
Line 40 expects `wrapper_args` to be a list instead of a tuple.
```python
wrapper_args.extend(args)
```
=> background helper: Fix a type error when initialising Task_proxy

pupil_src/shared_modules/audio_playback.py, pupil_src/shared_modules/audio_utils.py, pupil_src/shared_modules/av_writer.py, pupil_src/shared_modules/video_export/plugin_base/isolated_frame_exporter.py, pupil_src/shared_modules/video_export/plugins/world_video_exporter.py
Fixes #1475 by allowing any `audio*.mp4` to be loaded for audio playback.
- Uses `glob` to match potential audio files
- Prioritizes `audio.mp4` over `audio_xxxxx.mp4`
- Extracts loading of audio container, stream and timestamps into separate function and returns them as `LoadedAudio` namedtuple
- `Audio_Playback` and `Audio_Viz_Transform` make direct use of `LoadedAudio`
=> Allow any audio*.mp4 to be loaded for audio playback

pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
Fixes #1498
The Calibration Storage looks for recorded calibrations in `notify.pldata`. The resulting notifications are of type `file_methods.Frozen_Dict`. Consequently, the `mapper_args` dictionary of `notify.calibration.calibration_data` notifications is also a `Frozen_Dict`. If this `Frozen_Dict` is saved as is and later passed to the mapping process then it will be pickled on systems that spawn processes (macOS and Windows). Unpickling such `Frozen_Dict`s will call the `__setitem__()` function which will raise a `NotImplementedError` in this case.
The problem can be worked around by storing a normal dict instance of `mapper_args` instead.
=> Fix offline gaze mapper crash when using a recorded calibration

pupil_src/shared_modules/calibration_routines/optimization_calibration/__init__.py, pupil_src/shared_modules/cython_methods/__init__.py, pupil_src/shared_modules/pupil_detectors/__init__.py
Currently, when running from source, the built modules will be rebuilt (no-op) every time. This is problematic for a couple reasons. First, it means that the RUN environment has to have all of the includes and libs required to build the modules, even though they aren't all required to run the modules. Second, PyCharm debug mangles in-line Cython commands; see the bug report [here](https://youtrack.jetbrains.com/issue/PY-27833).
There is a work around available to the PyCharm-specific issue, but this disables automatic attaching to sub-processes, and this is a desirable feature given how pupil makes use of multiprocessing.
So this PR simply tries to import the compiled modules then if it fails, and if it's not the bundle, it then tries to build the required modules.
=> Even running from source, do not build modules unless required.

pupil_src/shared_modules/offline_reference_surface.py, pupil_src/shared_modules/offline_surface_tracker.py
The word "positions" was incorrectly spelled as "positons". This PR fixes the spelling in the logger as well as the file name `srf_positions_*.csv`
=> Fix typo in file name and logs - positons to positions

pupil_src/shared_modules/background_helper.py
This PR implements the option to specify as Task_proxy's multiprocessing contexts. This is helpful in situation where the Task_proxy is supposed to be started with a different context than the default, e.g. square marker detection on macOS.
Detailed information on multiprocessing contexts: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
=> Task_Proxy: Allow to specify multiprocessing context

pupil_src/shared_modules/audio_playback.py
Else the software crashes with
```py
File "/Users/papr/work/pupil/pupil_src/launchables/player.py", line 595, in player
p.recent_events(events)
File "/Users/papr/work/pupil/pupil_src/shared_modules/audio_playback.py", line 405, in recent_events
self.audio.timestamps[audio_idx]
IndexError: index 1534 is out of bounds for axis 0 with size 1534
```
=> Fix audio playback in cases where the audio is shorter than the world video

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/service_ui.py
By polling glfw events before updating pyglui we ensure that pyglui can react as fast as possible to ui events instead of waiting for a full processing cycle.
=> Improve ui responsiveness

pupil_src/shared_modules/eye_movement/controller/eye_movement_offline_controller.py, pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py, pupil_src/shared_modules/eye_movement/ui/menu_content.py, pupil_src/shared_modules/eye_movement/utils.py, pupil_src/shared_modules/eye_movement/worker/offline_detection_task.py, pupil_src/shared_modules/eye_movement/worker/real_time_buffered_detector.py
Calling `nslr_hmm.classify_gaze` function with invalid eye positions and/or timestamps causes the function to hang in an invalid state. This PR prevents calling this function with invalid data, and shows the user a message with the cause of the validation error.
This addresses the same problem as #1528 but specifically targets the manifestation of the problem.
=> Add gaze data input validation for NSLR-HMM classification

pupil_src/shared_modules/eye_movement/model/immutable_capture.py, pupil_src/shared_modules/eye_movement/model/segment.py, pupil_src/shared_modules/eye_movement/ui/menu_content.py, pupil_src/shared_modules/eye_movement/worker/offline_detection_task.py, pupil_src/shared_modules/eye_movement/worker/real_time_buffered_detector.py
Currently, the eye movement segment's `start_frame_index` and `end_frame_index` properties point inside the input buffer for `nslr_hmm.classify_gaze`. This PR updates these properties to represent indices into the capture video frame buffer.
=> Fix eye movement frame indices

pupil_src/shared_modules/camera_models.py, pupil_src/shared_modules/head_pose_tracker/function/bundle_adjustment.py, pupil_src/shared_modules/head_pose_tracker/function/triangulate_marker.py, pupil_src/shared_modules/surface_tracker/surface.py, pupil_src/shared_modules/update_methods.py
1. During [Merge branch 'master' into marc_surfaces_revamp](https://github.com/pupil-labs/pupil/commit/90b9be0), the definition of the function [undistortPoints](https://github.com/pupil-labs/pupil/blob/90b9be015759144469c7ecefb11a32730d9bbeee/pupil_src/shared_modules/camera_models.py#L547) was changed to fit Surfaces Revamp's usage. That would cause crush in head pose tracker during optimization of 3d markers model.
Therefore, `undistortPoints` is renamed as `undistort_points_on_image_plane` (for usages in e.g. Surfaces Revamp) and a new function `undistort_points_to_ideal_point_coordinates` is defined for the usages in head pose tracker.
1. Fix #1399: correct fisheye camera's solvePNP with None distortion.
1. Fix the intrinsic parameters in bundle adjustment for head pose tracker so …
=> Fix camera models

pupil_src/shared_modules/pupil_producers.py
Since the `pylgui.cygl.draw_points` shader does not support float64 precision, the sampled timestamps will be converted to float32. In cases in which float32 precision is not enough to sample a given number of distinct timestamps, the `pylgui.cygl.draw_points` function draws multiple (in float64 precision distinct timestamps) as a stack above each other.
This PR does not solve the issue of the float32 precision itself, but is just a work-around to avoid the stacked point drawings.
=> Sample pupil timelines with float32 precision

pupil_src/shared_modules/pupil_producers.py
Follow up PR for #1563 to avoid
```
2019-07-31 18:09:06,760 - player - [ERROR] launchables.player: Process Player crashed with trace:
File "launchables/player.py", line 504, in player
File "shared_modules/plugin.py", line 319, in __init__
File "shared_modules/plugin.py", line 361, in add
File "shared_modules/pupil_producers.py", line 255, in init_ui
File "shared_modules/pupil_producers.py", line 86, in init_ui
File "shared_modules/pupil_producers.py", line 149, in cache_pupil_timeline_data
IndexError: index 3580 is out of bounds for axis 0 with size 3580
```
=> Pupil timeline sampling: Use pm.find_clostest to avoid IndexError

pupil_src/shared_modules/video_capture/uvc_backend.py
This can happen after disconnecting/reconnecting on windows.
We shouldn't infer anything about this frame and discard it as invalid.
=> Drop frames with 0 timestamp in uvc-backend

pupil_src/shared_cpp/include/common/types.h, pupil_src/shared_modules/pupil_detectors/Tests/SphereCircleTests/VisualizeSphere.py, pupil_src/shared_modules/pupil_detectors/__init__.py, pupil_src/shared_modules/pupil_detectors/coarse_pupil.pxd, pupil_src/shared_modules/pupil_detectors/detector.pxd, pupil_src/shared_modules/pupil_detectors/detector_2d.pyx, pupil_src/shared_modules/pupil_detectors/detector_3d.pyx, pupil_src/shared_modules/pupil_detectors/setup.py, pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModel.cpp, pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModel.h, pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModelFitter.cpp
In some cases, one does not want the current eye model to change. This PR adds such an option to the 3d detector menu ("Freeze model") and the Pupil Detector Network API (#1390, `model_is_frozen` property).
**Warning**: Freezing the eye model will disable its ability to compensate for any kind of slippage.
You can freeze the eye model remotely by sending this notification to Pupil Capture:
```py
{
"subject": "pupil_detector.set_property.3d",
"name": "model_is_frozen",
"value": True,  # set to False to unfreeze
"target": "eye0",  # remove this line if you want to freeze the model both eyes
}
```
=> Add option to freeze current 3d eye model

pupil_src/shared_modules/surface_tracker/surface.py, pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
If no gaze data is available on a surface (either there is none or it is still being mapped in the background) the generated heatmap used to have resolution 1x1px. This PR changes this to always use the resolution implied by the smoothness value.
=> Surface Tracker Heatmap Resolution

pupil_src/shared_modules/surface_tracker/gui.py
- Fixes issue (#1589) where it was impossible to separate overlapping surfaces, because enabling edit mode for one surface would enable it for both, and moving the corner of one surface would move both corners of the overlapping surfaces.
- Fixes issue (#1590) where attempting to move a surface's corner would result in that corner being stuck to the mouse pointer.
- Fixes issue where moving the corner of surface A under the "edit" button of surface B would then make it impossible to move that corner elsewhere.
=> Surface tracker - fix GUI bugs

pupil_src/launchables/player.py, pupil_src/shared_modules/player_methods.py
=> Improve invalid recording errors

pupil_src/shared_modules/video_capture/utils.py
Before we calculated A SINGLE mean for all points.
This lead to a user-reported crash when using offline pupil detection with 3 negative time jumps in the eye video.
=> Correctly calculate different mean for all negative timejumps

pupil_src/shared_modules/video_capture/base_backend.py, pupil_src/shared_modules/video_capture/uvc_backend.py
Previously, the uvc backend did not check the provided YUV subsampling if a YUV buffer was available. pyglui only supports YUV 422 subsampling. If `update_from_yuv_buffer` was called with a different subsampling than YUV 422 it resulted in instabilities and incorrect rendering.
The internal conversion from YUV to BGR takes the subsampling into account correctly. Therefore, `update_from_ndarray(frame.bgr)` works correctly.
This change was not implemented in `Base_Source` since not all backends provide the `yuv_subsampling` attribute.
=> UVC Backend: Only call update_from_yuv_buffer if yuv subsampling is YUV422 

pupil_src/shared_modules/player_methods.py
Player crashed when moving the slider for the circle viz color to the limits.
pyglui seems to return values > 1.0 sometimes!
Fixes #1571
=> Fix circle color change crash

pupil_src/shared_modules/pupil_recording/info/recording_info.py, pupil_src/shared_modules/pupil_recording/info/recording_info_2_0.py, pupil_src/shared_modules/pupil_recording/update/invisible.py, pupil_src/shared_modules/pupil_recording/update/mobile.py, pupil_src/shared_modules/pupil_recording/update/old_style.py, pupil_src/shared_modules/recorder.py
This is because we are using different underlying version formats, e.g. Pupil Invisible might use semantic versioning for it's app_version.
Since we don't know anything about the version format and we only use it for display, we can savely just treat it as a string.
=> Remove all version parsing from Capture Software Version

pupil_src/shared_modules/pupil_recording/recording_utils.py
We forgot to handle the case where info.csv does not exist.
Returning False will just handle this gracefully via a UI message.
=> Fix missing info crash

pupil_src/launchables/player.py, pupil_src/shared_modules/pupil_recording/update/__init__.py
There is a known issue where multipart PI recordings sometimes have a world.mp4 and world.mjpeg file for the same part. Since the time information is lost, we cannot open these recordings.
Still we can gracefully handle this case and display an error message instead of crashing.
=> Catch pi duplicate world videos

pupil_src/launchables/player.py, pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py, pupil_src/shared_modules/gaze_producer/model/calibration_storage.py, pupil_src/shared_modules/head_pose_tracker/offline_head_pose_tracker.py, pupil_src/shared_modules/pupil_recording/update/__init__.py, pupil_src/shared_modules/video_capture/file_backend.py, pupil_src/shared_modules/video_export/plugins/imotions_exporter.py, pupil_src/shared_modules/video_export/plugins/world_video_exporter.py
When updating our recording format to the new info.player.json, we forgot to cleanup some references to the old-style info.csv that would crash when ran.
I patched up the offline calibration and head pose tracker quickly to use the new interface.
Some adjustments were required in order to make the new info data serializeable for background tasks.
The iMotions exporter needed some more work though since it requires to export an old-style info.csv which we now generate on export.
=> Fix old info references

pupil_src/shared_modules/av_writer.py
AV_Writer crashes on closing if the stream has not been configured correctly. Since AV_Writer only configures itself, after receiving at least one frame, a frameless recording resulted in an incorrectly configured stream and crashed Capture.
This PR only flushes the stream and writes timestamps if there was at least one frame.
=> Fix frameless recordings in Capture

pupil_src/shared_modules/gaze_producer/controller/calibration_controller.py
Fixes #1656
Problem:
`calibration.recording_uuid == self._recording_uuid` evaluates to `False` if one object is an UUID object, and the other a string. `calibration.recording_uuid` is a string for serialization reasons.
/cc @pfaion
=> Offline Calibration: Compare uuids correctly

pupil_src/shared_modules/pupil_recording/update/mobile.py, pupil_src/shared_modules/pupil_recording/update/old_style.py
Previously released versions of Pupil Player v1.16 do not support recordings created with
- Pupil Capture `v1.2` or earlier, and
- Pupil Mobile `r0.22.x` or earlier.
This was due to the fact that these recordings are missing meta information that is required for the upgrade to our new `Pupil Player Recording Format 2.0`. For details see "Missing Meta Information" below.
With this PR, instead of aborting with a "Recording too old" warning, Pupil Player will attempt to infer the missing values from other data in the recording. This inference is not perfect and results in imprecise values and might cause issues when converting recorded Pupil time to wall clock time. For details see "Missing Meta Information" below.
Since this inference is limited, we will remove the upgrade functionality for …
=> Support pre v1.3/r0.21.0 recordings in v1.16

pupil_src/launchables/eye.py
When closing the eye windows while recording, the process stopped without closing the writer.
This resulted in a broken recording for the stopped eye process.
The fix is to correctly close the writer on eye process end.
=> Gracefully terminate running recordings when eye process ends

pupil_src/launchables/eye.py, pupil_src/shared_modules/video_capture/base_backend.py, pupil_src/shared_modules/video_capture/fake_backend.py, pupil_src/shared_modules/video_capture/file_backend.py, pupil_src/shared_modules/video_capture/ndsi_backend.py, pupil_src/shared_modules/video_capture/realsense2_backend.py, pupil_src/shared_modules/video_capture/realsense_backend.py, pupil_src/shared_modules/video_capture/uvc_backend.py
Eye already uses a couple of plugins but has to manage them manually.
This results in a lot of duplicate code that is all over the place but belongs together.
World uses the PluginList to extract this logic.
I added a PluginList to eye and extracted the plugins into it.
Some refactoring was required for resolving order-of-execution issues.
This will also allow us to make plugins out of the detectors and integrate them more cleanly,
=> Use PluginList in eye process

pupil_src/shared_modules/surface_tracker/background_tasks.py, pupil_src/shared_modules/surface_tracker/surface.py
Fixes #1616
Since version 1.13, the surface tracker defines surfaces in [3d camera space][terms] instead of [2d image space]. Accordingly, the surface tracker exports the homography matrices to transform coordinates between the _undistorted camera coordinate system_ and the surface, and vice versa.
If one wants to crop the surface from the distorted scene image, e.g. the surface debug view, one needs specific homographies that transform between the surface and the _distorted image space_. These matrices are not beeing exported yet.
This PR adds export functionality for these homographies by adding two further columns to the `surf_positions<name>.csv` file:
- `dist_img_to_surf_trans`
- `surf_to_dist_img_trans`
These columns contain the corresponding matrix values.
[terms]: …
=> Export homography matrices for transforming between distorted image and surface coordinates

pupil_src/shared_modules/surface_tracker/background_tasks.py
Example outputs
1x1:
40x10:
40x100:
=> Scale heatmap export based on surface size

pupil_src/shared_modules/surface_tracker/surface.py
When defining a new surface, markers from a few frames before and after are aggregated to ensure more stable marker mappings.
This is a problem when the surface is defined in a section where the markers flicker a lot. The bounding boxes are not mapped appropriately and thus the surface definition contains erroneous marker locations. This error will bleed over into the whole mapping. Most importantly it can result in jumping boundaries when only a subset of the markers is visible of which a majority was incorrectly mapped at definition.
The quick fix is here to just don't scan neighboring markers on surface definition. Especially with the new apriltags there is no need to do temporal smoothing anymore.
@papr In the long run we should refactor the surface tracker to get rid of all the code …
=> Fix unstable surface outlines

pupil_src/shared_modules/surface_tracker/surface_online.py, pupil_src/shared_modules/surface_tracker/surface_tracker_online.py
The setter function referred to `gaze_history_length`, while all other parts of the code referred to `GAZE_HISTORY_LENGTH`. I changed everything to lower-case since it's supposed to be modified and not constant.
=> Fix heatmap history length setter not working

pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/video_export/plugins/world_video_exporter.py
The current implementation of the eye movement detector might not be doing what we actually want. Until we have time to review this, we disable the detector.
=> Disable eye movement detector

pupil_src/shared_modules/surface_tracker/background_tasks.py
We decided to have a fixed heatmap size of min 2000px for export.
Also I got rid of the alpha channel for export since Windows has sometimes issues with displaying PNGs with constant alpha nicely.
=> Fixed heatmap export dimension

pupil_src/shared_modules/video_capture/utils.py
There have been reports of 1 frame missing in raw data compared to the timestamps.
Here we skip the last timestamp in this case.
=> Gracefully handle mismatches between time and raw for PI recordings

pupil_src/shared_modules/pupil_recording/recording_utils.py, pupil_src/shared_modules/pupil_recording/update/mobile.py, pupil_src/shared_modules/pupil_recording/update/old_style.py
This reverts commit 27f9153effd04cc160666416386e83989509a677, reversing changes made to 64a3ac418747b7789b7a1e2bf4d52bfc66ad91e9. Attempts to open deprecated recordings in Player v1.18 will show a notification asking the user to perform the required data format update in Pupil Player v1.17
=> Remove support for updating deprecated recordings

pupil_src/shared_modules/pupil_recording/info/__init__.py, pupil_src/shared_modules/pupil_recording/info/recording_info.py, pupil_src/shared_modules/pupil_recording/info/recording_info_2_1.py, pupil_src/shared_modules/pupil_recording/update/invisible.py, pupil_src/shared_modules/pupil_recording/update/new_style.py, pupil_src/shared_modules/video_capture/utils.py
This is important because there was an additional debug file introduced to PI recordings, called `gaze_right ps*_timestamps.npy` which (currently) only contains zeros.
With the previous pattern we intended to match all gaze files for multipart recordings, but now we would include these erroneous zeros, leading to jumps in the gaze data. Specifically these files were corrupted:
* `gaze.pldata`
* `gaze_timestamps.npy`
**So currently when opening a normal single-part PI recording, every second gaze point will be (0,0)!**
Even worse: the gaze timestamps are only generated once upon upgrading of the PI recording to newstyle. This cache is now incorrect and we will have to create an update mechanism for all PI recordings that have been opened once with Player < v1.18.
=> Fix corrupted gaze data from latest PI recordings

README.md
Not sure if a markdown table is the nicest way to format this, but I thought it's less heavy than listing the entire 3 help messages for Capture/Player/Service here.
=> Add documentation for CLI arguments

pupil_src/main.py, pupil_src/shared_modules/pupil_remote.py
In most cases you don't want the port to get saved in the settings anyway, especially since capture will generate a random free port when the default port is in use.
* Removes port interface of Pupil_Remote
* Moves default port settings to CLI arg defaults
Note that the argparser ensures that the **port** arg is an int, so no need for the typecheck anymore.
Fixes #1462
=> Fix `None` port in Pupil Service

pupil_src/run_capture.bat, pupil_src/run_player.bat, pupil_src/run_service.bat
Not sure if this worked at some point before, but we want to be able to pass our CLI args also when running the apps on Windows, e.g. with `run_capture.bat --hide-ui`
=> Forward CLI args of windows run_*.bat files appropriately

pupil_src/launchables/service.py, pupil_src/shared_modules/pupil_remote.py
The problem was that the shutdown of Service would be so fast that the eye processes were not started up completely.
Thus the cleanup at the end of Service was not received by the eye-processes yet and they would be kept alive.
Preventing the eye processes from starting in case of an initialization failure was way easier to implement and provides better UX than waiting for the eye processes to finish startup before shutting down Service.
=> Correctly shutdown Service if port is already in use

pupil_src/shared_modules/av_writer.py
Fixes #1680 
TODO:
In order to facilitate seeking to a given timestamp, Player now exports the video presentation timestamps (pts) for each exported frame. The data is stored in an additional `pts` column in the corresponding `*_timestamps.csv` file.
=> Export pts in *_timstamps.csv file

pupil_src/shared_modules/av_writer.py
This is because we are checking the packet's stream in AV_Writer now.
=> Set JPEG_Writer packets.stream to videostream

pupil_src/shared_modules/pupil_recording/recording_utils.py
Opening an unopened Pupil Mobile recording in Pupil Player would cause a crash with:
```
File "---\pupil/pupil_src\launchables\player.py", line 835, in player_drop
update_recording(rec_dir)
File "---\pupil\pupil_src\shared_modules\pupil_recording\update\__init__.py", line 68, in update_recording
_transformations_to_new_style[recording_type](rec_dir)
File "---\pupil\pupil_src\shared_modules\pupil_recording\update\old_style.py", line 42, in transform_old_style_to_pprf_2_0
_update_recording_to_old_style_v1_16(rec_dir)
File "---\pupil\pupil_src\shared_modules\pupil_recording\update\old_style.py", line 144, in _update_recording_to_old_style_v1_16
update_recording_v0913_to_v13(rec_dir)
File "---\pupil\pupil_src\shared_modules\pupil_recording\update\old_style.py …
```
=> Fix unopened Pupil Mobile recordings being detected as old-style

pupil_src/tests/test_csv_utils.py
Python's csv library specifies that files passed to csv readers/writers have to be opened with `newline=""` or this won't work on windows.
See https://docs.python.org/3/library/csv.html#id3
=> Fix csv test  not working on windows

pupil_src/shared_modules/plugin.py
There was a problem where in Player the eye-proces (offline detection) initialized the UVC source plugin, which tried to install drivers on windows. This should not happen, because we don't need UVC in player and actually overwrote the video source.
The problem was that the plugin initializers would be called before filtering the list by uniqueness.
I added filtering of the initial `__init__` list before constructing the initial set of plugins.
All the logic in .add() stayed untouched.
=> Plugin_List unique initialization

.travis.yml, .travis/run_tests.sh
I removed the old (unused) travis config and replaced it with a new one.
Currently there's only a pytest run in an Ubuntu 18.04 docker image.
=> Let travis run pytest

.travis/run_tests.sh
Currently there seems to be an issue where pytest 5.2.3 runs the calibration module (although this one is not tested).
Since we don't have the dependencies setup yet on travis, this will crash.
=> Downgrade pytest to 5.2.2

pupil_src/shared_modules/surface_tracker/gui.py
Currently Capture and Player crash when clicking "add/remove markers" while the legacy square marker detector is selected.
The cause is a wrong function call, likely from earlier refactors.
=> Fix broken function call for square markers

pupil_src/shared_modules/surface_tracker/surface_tracker.py, pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
I found two inconveniences when passing by the surface tracker:
1. Selecting the same detection mode would recalculate the cache (although nothing changed)
2. Switching the detection mode would log raised exceptions on Windows because of incomplete cleanup.
=> Surface cache improvements

pupil_src/shared_modules/video_capture/utils.py
If the path contains glob symbols (e.g. []) this will do bad things.
So we only glob the files inside, but not on the path.
Also I refactored the list-comprehension, because this way we don't have to instantiate the `Video(loc)` twice.
=> Don't use glob on the full path

pupil_src/shared_modules/calibration_routines/gaze_mappers.py
This PR changes the binocular gaze mapper to use a temporal cutoff based on the estimated FPS of the pupil data stream.
=> Temporal cutoffs in binocular gaze mapper based on estimated FPS

pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/fixation_detector.py
Earlier to #1743, the manual marker and screen marker calibrations could be sped up when the Online Fixation Detector was active. This was possible since it used the 3d eye model to calculate fixations. Due to consistency reasons, see 515783161abdf0165ab1898ae2ac83b992916251 for details, we have decided to disable this functionality. Instead the fixation detector always requires calibrated gaze which is not available during the calibration.
=> Remove calibration fixation boost

pupil_src/shared_modules/video_capture/utils.py
Without the `*`, video lookup tables will only use the first part of the recording.
=> Fix regression when fetching multi-part videos in VideoSet

README.md
There have been a few users who are not familiar with GitHub having difficulty finding out where to download the latest application bundles. 
I propose to add an image here with a "button" within the image that links to releases/latest. For sake of redundancy I also propose to leave the text link "download the latest apps" - but I am open to suggestions of removing this.
=> Add explicit link for downloading app bundles

pupil_src/shared_modules/video_capture/utils.py
Fixes `av_frame is referenced before assignment` crash in file backend if video is actually empty but was not recognized as such.
=> Correctly handle empty video files

pupil_src/shared_modules/gl_utils/utils.py
Currently, the Python OpenGL bindings perform an explicit error check after each call. For better debugging, it keeps track of the current OpenGL call. If an opengl error occurred before the check, that was not explicitly checked, the bindings error checker will trigger but print the wrong context.
This PR attempts to work around this by emptying the opengl error queue and only logging the exceptions instead of raising them.
Caveat: In case of OpenGL errors, this might result in unexpected visual effects instead of crashing the application.
=> Custom gl error

README.md
So users are directed directly to the bottom of the release notes.
=> Add link anchors to download section in release notes

.gitignore, deployment/bundle.bat, deployment/deploy_capture/bundle.spec, deployment/deploy_player/bundle.spec, deployment/deploy_service/bundle.spec, pupil_external/vc_redist/README.txt
[edited by @pfaion ]
This makes sure that #1661 does not happen anymore on Windows systems without the latest Microsoft Visual Studio Redistributable libraries.
=> Include missing dll dependencies in Windows bundle

pupil_src/launchables/marker_detectors.py
Fill gaps on circle marker detection to have correct frame indices.
This fixes the visualization of the circle markers being off when there are gaps before the markers, e.g. from the calibration procedure before validation markers.
=> Fix circle marker visualization after gaps

pupil_src/launchables/eye.py, pupil_src/launchables/service.py, pupil_src/launchables/world.py
The --hide-ui flags were missing in the *_profiled launchables.
This was started by #1759 but service_profiled was missing.
I quickly made a new PR for being able to include this in today's release.
=> Enable combination of --hide-ui and --profile flags

pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py, pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py
This PR fixes the offline pupil detection displaying the algorithm view by default.
Additionally it disables rendering the algorithm view when `display_mode` is not `"algorithm"`.
Previously we would always render the algorithm view, even when not in algorithm mode.
This could potentially have a big impact on performance.
=> Only render detector debug views in algorithm mode

pupil_src/launchables/eye.py, pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py, pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py
Currently we update the Roi too late when switching resolutions, resulting in a bad Roi being passed to the pupil detectors. This can cause crashes on the C++ side, so I caught these cases here.
Long-term we should make a plugin out of the roi and handle everything in the correct order.
=> Don't detect pupils when ROI out of frame bounds

pupil_src/shared_modules/video_capture/__init__.py
Not having realsense installed is actually the normal use case, so most of the users would get the log info message and did not know what it was about. It was decided to switch the realsense info to level `debug`.
=> Adjust realsense loglevel

docs/dependencies-macos.md, docs/dependencies-ubuntu17.md, docs/dependencies-ubuntu18.md, docs/dependencies-windows.md
When pip is too old, the installation of e.g. pupil-apriltags will fail.
See issue there: https://github.com/pupil-labs/apriltags/issues/13
This looks like an issue of Pupil when just running the pip install commands from the docs, which probably inspired PR #1775 
Adding exlicit upgrade instructions should get rid of this issue.
As this is user-facing docs-only, we should merge into master.
=> Add pip upgrade instructions to README

pupil_src/launchables/eye.py
The ROI-mouse-interaction has been accidentally removed when adding the Plugin workflow to eye.py This PR adds this back in.
Note that we have planned to move the ROI code to an actual plugin as well, which will allow us to get rid of all the duplicate logic between ROI and plugins.
Closes #1777
=> Add ROI mouse-interaction back in

pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/glfw.py
This PR fixes a couple of bugs with the screen marker calibration window:
- On Windows the window won't be black on open anymore
- Capture won't crash anymore (or throw errors) when tabbing out of the calibration
- The calibration will stop when the window is closed/minimized/tabbed out
- The cursor will be captured in fullscreen mode. This reduces the risk of accidentally tabbing out when having more than 1 monitor.
@papr please test all kinds of shenanigans with the calibration window on macOS
=> Fix fullscreen calibration

docs/dependencies-macos.md, docs/dependencies-ubuntu17.md, docs/dependencies-ubuntu18.md, docs/dependencies-windows.md
I added a unified note that virtualenvs are recommended. Reasons:
- e.g. PIMonitor has conflicting dependencies with Pupil
- when using a virtualenv you can just run `pip` everywhere instead of having to decide between `pip` and `pip3`
- you don't need `sudo pip` when installing into a virtualenv
Since virtualenvs have trouble with `apt` installed Python packages on Ubuntu, I extended the notes on troubleshooting the OpenCV Python bindings. Also those were missing in the Ubuntu 18 docs. See this PR: #1775 for an example of how this can confuse users.
@papr does the trouble with system-installed opencv-python-bindings in virtualenvs also apply to macOS? Then we should add a note there as well. I found the [`--system-site-packages`](https://virtualenv.pypa.io/en/latest/userguide/#the-system- …
=> Virtualenv docs

pupil_src/shared_modules/audio_capture.py, pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py, pupil_src/shared_modules/calibration_routines/single_marker_calibration.py, pupil_src/shared_modules/camera_intrinsics_estimation.py, pupil_src/shared_modules/video_capture/file_backend.py, pupil_src/shared_modules/video_capture/realsense2_backend.py, pupil_src/shared_modules/video_capture/realsense_backend.py, pupil_src/shared_modules/video_capture/uvc_backend.py
There's a potential race conditon with pylgui Selector selection_getter.
This is very unlikely as it can only happen when the selection list changes between having clicked on the selector and the next redraw. Still, I added notes in the vulnerable places.
Note that most of those places will get deprecated soon anyways with the video source skimming.
=> Pyglui selector racecondition notes

pupil_src/launchables/player.py, pupil_src/launchables/world.py
Once https://github.com/pupil-labs/pyglui/pull/112 has been merged.
=> Bump minimal pyglui version to 1.27

pupil_src/shared_modules/data_changed.py, pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py, pupil_src/shared_modules/fixation_detector.py, pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py, pupil_src/shared_modules/gaze_producer/gaze_from_recording.py, pupil_src/shared_modules/gaze_producer/gaze_producer_base.py, pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
=> Use Announcer and Listener for gaze data change

pupil_src/shared_modules/raw_data_exporter.py
This PR fixes that for monocular gaze datums, the raw data export would always only populate the eye0 column for `eye_center_*` and `gaze_normal_*`, even if the data was taken from eye1.
Also I applied black and cleaned up the imports.
=> Fix monocular data export

pupil_src/shared_modules/video_export/plugins/eye_video_exporter.py, pupil_src/shared_modules/video_overlay/ui/management.py, pupil_src/shared_modules/video_overlay/utils/image_manipulation.py
This PR adds the green eyeball outline visualization to the following **Player** plugins:
- eye overlay
- eye video export
The existing switch for toggling pupil ellipse visualization has been adjusted to include the eyeball outline as well.
When 3D data is not available, we only show the pupil ellipse just as before.
=> Eyeball Outline for Player

pupil_src/shared_modules/video_capture/uvc_backend.py
Sometimes UVC might provide us with non-monotonic timestamps.
If we don't drop these frames, we might crash somewhere else.
=> Drop frames with non-monotonic timestamps in uvc

pupil_src/shared_modules/video_capture/uvc_backend.py
Issue: The time monotonicity check introduced #1812 happens after applying the time sync offset. If this offset is negative, the check will fail and drop frames until the offset has passed.
This PR reverts pupil-labs/pupil#1812 and places the check before applying the timesync offset.
=> Fix "Drop frames with non-monotonic timestamps in uvc"

pupil_src/shared_modules/roi.py
Fixes #1825 
I think `not self.has_frame` should already be sufficient, but I noticed that I safe-guarded the other plugin-lifecycle functions (`gl_display`, `on_pos`) already in the same way, so for consistency (and double safety) I also check `model.is_invalid()`.
=> Do not process on_click events when there's no frame

pupil_src/shared_modules/video_capture/utils.py
The old implementation raises a TypeError as `av.AVError` expects an additional error code. Instead of passing any error code, the new implementation raises (and catches) a custom error in the case that a video is valid but does not contain any frames.
=> Use custom error if video does not have frames

pupil_src/shared_modules/video_capture/ndsi_backend.py
@papr did we need the previous `.dev0` suffix? I removed it for the bump as I couldn't see anything on NDSI.
=> Bump ndsi version to v1.3

pupil_src/shared_modules/video_capture/uvc_backend.py
This PR fixes multiple issues on Windows with Unicode characters and spaces in the path to Pupil.
Most notably `libwdi` cannot handle non-ASCII characters in the path to unpack and install drivers to/from. This was bypassed by checking the working directory for ASCII compatibility and using `C:\Windows\Temp` (specifically, to avoid non-ASCII characters in potential default TEMP directory) as fallback location.
By using a new temporary folder for every driver, potential permission errors that occurred when cleaning up folders created by elevated commands have also been prevented. A frequently occurring error due to unescaped spaces in the old cleanup routine was thereby also fixed.
=> Fix windows path issues

pupil_src/launchables/eye.py, pupil_src/shared_modules/av_writer.py, pupil_src/shared_modules/recorder.py
When timestamps are handled from external sources, the sources need to take care of syncing time. This can lead to jumps in timestamps when syncing while recording.
Since the video writer classes work under the assumption of monotonic data, we cannot handle negative time jumps caused by syncing. Previously Capture would just crash when receiving a negative time jump.
This PR handles negative time jumps more gracefully:
- A running recording will be stopped, so the partial recording is useable
- An error message will be shown, more detailed information will be logged as debug info
- Capture does not crash anymore
=> Stop nonmonotonic recording

.travis/run_tests.sh
This needs to be added once we release NDSI v1.3 in order for the Travis tests to run.
To check if this works, first, re-run Travis on this commit.
=> Update pyndsi on travis before testing

pupil_src/shared_modules/video_capture/uvc_backend.py
Fixes #1841 by passing absolute path of PupilDriverInst.exe to powershell command.
=> Fix #1841 by passing absolute path of PupilDriverInst.exe

pupil_src/launchables/eye.py
The right eye camera (`Pupil Cam1/2/3 ID0`) is assembled upside-down in the Pupil Core headset and VR/AR-addons. The eye process has always allowed the user to flip the eye video preview in the eye windows' general menus.
With this PR we are enabling this option by default for the right eye camera.
=> Flip eye0 video preview by default

deployment/deploy_capture/bundle.spec, deployment/deploy_player/bundle.spec, deployment/deploy_service/bundle.spec
libuvc and its dependencies should automatically be detected when importing pyuvc during bundling.
Reverts bd3c72a81b9bde464c5ff45e54d636ecf3ffdcb5
=> Remove manual libuvc copy for macOS bundles

docs/dependencies-ubuntu17.md
`ppa:jonathonf/ffmpeg-3` is no longer available. Instead [`ppa:jonathonf/ffmpeg-4`](https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4) can be used.
=> Ubuntu 16.04: ffmpeg-3 ppa no longer available

pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py, pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py, pupil_src/shared_modules/pupil_producers.py
Add detector identifiers to pupil topics
Breaks here https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/pupil_producers.py#L227 when opening a recording that was recorded with this commit.
To fix this `PupilDataBisector` needs to be applied to `PupilFromRecording`
=> Add detector topic tags

pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py, pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py, pupil_src/shared_modules/pupil_detector_plugins/detector_base_plugin.py
This PR modifies the detector plugins in order to allow running 2D and 3D detectors in parallel, without having the 2D detector twice.
This branch only work together with https://github.com/pupil-labs/pupil-detectors/pull/9
=> Decouple dual detectors

pupil_src/launchables/player.py, pupil_src/shared_modules/blink_detection.py, pupil_src/shared_modules/gaze_producer/controller/gaze_mapper_controller.py, pupil_src/shared_modules/gaze_producer/worker/map_gaze.py, pupil_src/shared_modules/gaze_producer/worker/validate_gaze.py, pupil_src/shared_modules/player_methods.py, pupil_src/shared_modules/pupil_producers.py, pupil_src/shared_modules/system_timelines.py, pupil_src/shared_modules/video_export/plugins/eye_video_exporter.py, pupil_src/shared_modules/video_export/plugins/world_video_exporter.py, pupil_src/shared_modules/video_overlay/plugins/eye_overlay.py
Fixes #1851 
Removes `g_pool.pupil_positions_by_id[id_]`. Use `g_pool.pupil_positions[id_, :]` instead.
=> Use pupil data bisector as g_pool.pupil_positions

pupil_src/shared_modules/pupil_producers.py
Switches diameter timeline from 2d pixels to 3d millimeters. Filters outliers using [Tukey's fences](https://en.wikipedia.org/wiki/Outlier#Tukey's_fences) and shows displayed range in timeline legend.
Previously:
Afterward:
This makes the timeline consistent with the realtime diameter 3d graph in Capture.
=> Diameter 3d timeline

pupil_src/shared_modules/video_capture/uvc_backend.py
There was a user who could not install the drivers on Windows.
The cause seemed to be that `Path.cwd()` returned `C:\Windows\system32` for no apparent reason, although the bundle was located in a different folder.
This PR will rely on using the bundle path taken from `sys` instead.
Additionally, I fixed another potential issue where the Unicode check would not properly work if the bundle was installed to a location outside of the user's home folder, but the home folder would still contain Unicode characters.
=> Fix windows driver issues v2

pupil_src/shared_modules/video_capture/uvc_backend.py
Previous version did only break out of inner loop but not the outer loop. This caused the selection to continue instead of using the first found match.
=> Fix preferred camera selection

pupil_src/shared_modules/blink_detection.py, pupil_src/shared_modules/player_methods.py, pupil_src/shared_modules/pupil_producers.py, pupil_src/shared_modules/raw_data_exporter.py, pupil_src/shared_modules/system_timelines.py
- Caches `PupilBisector.__getitem__`, effectively avoiding combination the same bisectors over and over again
- Stop converting `Bisector.data` to `list`, avoiding reconversion to `ndarray` down the line
- Might cause issues when serializing slices of `g_pool.pupil_positions`, etc. In this case, call `data_slice.tolist()` before serializing
- Requires compatibility tests with all Player plugin
Considerable time is spent when serializing data for a background process. We should think about a method of transferring the data bit-by-bit, instead of in a bulk.
Most of the performance comes from decoding images into RGB buffers and manipulating them. Nothing we can do about right now.
=> Improving Player performance

pupil_src/shared_modules/pupil_producers.py
Issue: If no 2d pupil data is available the confidence timeline stays empty even though 3d confidence data is available.
Solution: Fallback to 3d confidence data if available.
=>  Confidence timeline: Fallback to 3d confidence if no 2d data is available

pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py
When both detectors are running in parallel, the 2D settings of the 3D plugin are not used anymore.
I also removed the large info text about the algorithm view from the 3D plugin, since it is only used for debugging the 2D settings.
2D UI (unchanged):
New 3D UI:
=> Remove 2D settings from 3D detector UI

pupil_src/shared_modules/pupil_detector_plugins/detector_2d_plugin.py, pupil_src/shared_modules/pupil_detector_plugins/visualizer_2d.py
This will color the 2D ellipse visualization in blue, which helps now that we have both 2D and 3D detectors running in parallel. This change affects both Capture and Player.
I also increased the polygon count of the ellipse outline to match that of the 3D eyeball visualization for a smoother pupil. After some testing, I did not touch the thickness, so pupil ellipses are still drawn with 1px, while the eyeball outline has 2px as before.
Example:
=> Draw 2D pupil ellipse in blue and cleanup code

pupil_src/shared_modules/video_overlay/utils/image_manipulation.py
This makes the Player 2D ellipse visualization color compatible with the new color for Capture, see #1873
=> Change 2D ellipse outline color to light blue

pupil_src/shared_modules/video_capture/uvc_backend.py
Since v1.22 Pupil Capture does not offer built-in support for Intel RealSense cameras anymore. The cameras would still show up in the camera selection list, although activating them would have no effect. This would confuse users, as they could use the cameras previously.
This PR filters out all cameras with **RealSense** in the name from the camera activation list.
TODO:
=> Hide realsense cameras in camera selection list

pupil_src/shared_modules/plugin.py
Changes previous behavior where running `by_class` unique plugins could not be replaced.
This behaviour is especially problematic if `by_class` plugins are started by default. In this case, there would not be a possibility to change their configuration.
With the new behaviour, a new configuration can be loaded by restarting the plugin with the new config. The old plugin will be removed.
=> Allow replacing `by_class` unique plugins

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/service.py, pupil_src/launchables/world.py, pupil_src/main.py, pupil_src/shared_modules/plugin.py
We often receive OpenGL errors as results of buggy pyglui code that gets called in `gl_display()` of plugins. Since pyglui does not check `glGetError()`, we run into these errors at other places at the code when e.g. using pyopengl. By checking after every plugin's `gl_display()` call we can at least partially localize the error!
Since it's easy to skip calling the base `Plugin.gl_display()` from subclasses, I monkeypatched a wrapper into all subclasses.
=> Add glGetError() check to every Plugin.gl_display()

pupil_src/shared_modules/pupil_recording/info/__init__.py, pupil_src/shared_modules/pupil_recording/info/recording_info_2_2.py, pupil_src/shared_modules/pupil_recording/update/new_style.py
Add recording info meta version 2.2.
Upgrade Pupil v2.0 recordings to be incompatible with Pupil v1.x.
=> Bump recording info version for Pupil v2.0

pupil_src/shared_modules/plugin.py
Gazer2D and Gazer3D did not correctly replace each other.
I found the bug in the replacement logic and fixed it:
`base_class()` is a class method and therefore no property and needs to be called.
For clarity I also replaced all mentions of `__bases__[-1]` with a call to `base_class()` since this is the appropriate abstraction we already have.
=> Fix base class duplicate

pupil_src/shared_modules/gaze_producer/controller/gaze_mapper_controller.py, pupil_src/shared_modules/gaze_producer/model/gaze_mapper.py, pupil_src/shared_modules/gaze_producer/ui/gaze_mapper_menu.py, pupil_src/shared_modules/gaze_producer/ui/gaze_mapper_timeline.py
If a GazeMapper did not produce any data, e.g. because the pupil data had the wrong method, it would still show `"Successfully completed mapping"` in the UI, but the timeline was grayed out.
I changed it so that you get a warning in this case that your GazeMapper did not produce any data.
=> Add feedback for empty GazeMapper

pupil_src/shared_modules/gaze_producer/model/gaze_mapper.py
I had 2 offline Gaze Mappers and deactivated one. As a result there was a lot of weirdly duplicated and wrong data in the gaze export.
I did not figure out the whole chain of what was going wrong but stumbled across this piece of code. Never use mutable types as default parameter values! After fixing this the problem disappeared for me.
Since I didn't fully validate that this was indeed the cause of the problem, maybe see if you can reproduce the issue before (and not afterward).
=> Fix gaze corruption when deactivating gaze mappers

pupil_src/shared_modules/surface_tracker/surface.py
Player would crash when adding a new surface.
The problem was that
```python
None in (ndarray1, ndarray2)
```
gets internally computed with:
```python
any(None is x or None == x for x in (ndarray1, ndarray2))
```
which finally results in an `any` of multiple numpy arrays, resulting in 
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
=> Fix crash when adding a new surface

pupil_src/shared_modules/data_changed.py
Fixes the following bug:
1. Have a recording with stored data for both recording and offline data for both pupil and gaze.
1. Select **Pupil from Recording** and compute the **Offline gaze mapper**.
1. Switch to **Gaze from Recording**.
1. Switch to **Offline Pupil**.
1. Switch back to **Offline gaze mapper**.
Result: The offline gaze mapper displays the gaze that was mapped previously to **Pupil from Recording**, although we currently have **Offline Pupil** selected.
---
**BUT (!!)**
@papr @romanroibu 
This PR fixes the obvious bug. But I'm not sure that what's happening is actually the intended behavior. The `Offline_Pupil_Detection` will always call `announce_new()` when loading existing data from storage, should it be `announce_existing()` in that case? Otherwise we create a new token …
=> Fix Announcer not storing new tokens in instance

pupil_src/shared_modules/calibration_choreography/single_marker_plugin.py, pupil_src/shared_modules/network_api/network_api_plugin.py
- Set the default mode for Single Marker Calibration to `MANUAL`
- Renamed the `MANUAL` mode label in Single Marker Calibration to `"Physical Marker"`
- Fixed to label name for `NetworkApiPlugin` to consistently show `"Network API"`
=> Small improvements for Pupil Core v2 (1)

pupil_src/shared_modules/blink_detection.py
Since we run 2d and 3d pupil detection in parallel, we need to filter one type of pupil data in order to get a clean confidence signal. Since the 2d confidence signal provides sharper confidence drops during blinks, this PR changes the real-time blink detector to only use that signal.
This makes the real-time blink detector consistent with the post-hoc detector d2516d29bca3704044759d84d0e9c09a2c474a34
=> Use only 2d confidence in realtime blink detector

pupil_src/shared_modules/player_methods.py, pupil_src/shared_modules/pupil_producers.py
Instead of using `Mutable_Bisector`s (which use `nump.insert`), use a timestamp->datum mapping. This has the advantage of being faster and avoids duplicated entries when restarting the detection while there is an existing detection running.
This PR also correctly announces cached pupil data as "existing" instead of "new". This avoids recalculating e.g. offline gaze mappings on restoring a session.
=> Improve Offline Pupil Detection data storage during detection

pupil_src/shared_modules/blink_detection.py
(@pfaion added:) The blink detector visualization currently interferes with the visualization of the system graphs and introduces visual bugs. We have decided to remove the visualization for now as the actual fix might not be completely straightforward.
=> Remove blink detection visualization

pupil_src/shared_modules/calibration_choreography/base_plugin.py
The code would crash when a child-class did not overwrite `selection_label` as the base class implementation was faulty.
This didn't happen internally as all our child classes overwrite `selection_label`, but the HMD plugin didn't, so I found this while testing HMD.
=> Fix NameError when not overwriting selection_label

pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_hmd.py
These are required for starting the HMDGazer and thus restoration from
session settings will fail otherwise.
This is a quick fix preventing the crash.
The more general question is if we want the HMD gazer to start at all, I'll create a ticket for that.
=> Store HMD eye_translations in session settings

.travis/run_tests.sh
Since v2.0 we were getting errors on CI.
This was simply because we were running with an old PyAV version.
=> Update PyAV on travis

pupil_src/shared_modules/player_methods.py
MutableBisector calls numpy.insert on self.data. The `numpy.insert()` documentation states that it will attempt to convert the inserted value to the dtype of the array. https://numpy.org/doc/1.18/reference/generated/numpy.insert.html
This currently fails for post-hoc annotations and head pose tracking as self.data is not an object-array.
=> Fix MutableBisector.insert()

pupil_src/shared_modules/calibration_choreography/base_plugin.py, pupil_src/shared_modules/calibration_choreography/hmd_plugin.py
Fixes HMD3DChoreographyPlugin crash in Service, as Service does not initialize any plugin UI. See dedicated change commit: https://github.com/pupil-labs/pupil/commit/e2d5170d046d9ec1e580380f1cc94f6ea899dc9b
=> Choreography plugins: Only call update_ui() in Capture

pupil_src/shared_modules/gaze_producer/model/legacy/calibration_storage_updater.py
This PR fixes that imported v1 offline calibration from a different recording will be updated to v2.
No read-only calibrations (recorded or imported) should be updated.
Please note:
I consider this a _quick fix_.
I don't like duplicating the `recording_uuid == calib.recording_uuid` already a third time, but unfortunately there is no easy way of using one of the other methods here without rewriting a lot of other code.
I would have liked if the update mechanism was a member function of the `CalibrationStorage`, but I guess that was not possible since it's `__init__()` has so many side-effects and non-inverted dependencies.
Maybe you have additional thoughts on that.
=> Fix updating imported v1 calibs

pupil_src/shared_modules/gaze_producer/model/calibration.py, pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
This PR fixes that recorded calibration are displayed as modifiable.
I would also argue for removing `__assert_property_consistency()` completely.
To me, it's not clear when this should be called and when not.
It's called twice in a very general (?) try-except:
```python
try:
self.__assert_property_consistency()
except ValueError:
raise
except Exception as err:
raise ValueError(str(err))
```
and once without any try-except, just raising (and probably crashing):
```python
@property
def as_dict(self) -> dict:
self.__assert_property_consistency()  # sanity check
dict_ = {k: v(self) for (k, v) in self.__schema}
return dict_
```
=> Fix modifiable recorded calibrations

pupil_src/shared_modules/gaze_producer/ui/calibration_menu.py
This PR fixes that recorded calibrations can be duplicated.
The changes will only make sense once #1932 has been merged. 
Since they are not modifiable, duplicating them does not make sense as the copy would also be non-modifiable.
=> Prevent duplication of recorded calibration

pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
This PR prevents imported recorded calibrations from messing up the numbering scheme of internal recorded calibration naming.
If we had a **Recorded Calibration** and imported a calibration with name **Recorded Calibration**, the calibration actually belonging to the recording might be renamed to **Recorded Calibration 2**.
=> Prevent inconsistent naming of recorded calibs

pupil_src/shared_modules/tasklib/manager.py
This is a pure refactoring PR, no behavior should change.
The `PluginTaskManager` previously remembered the state of its tasks by splitting them into two lists (added vs running), although the tasks also know their state (and even own it). This can cause problems (there are even comments for when these assumptions were wrong in the past). Refactoring the `PluginTaskManager`  in this way to cleanup the behavior will make a planned bugfix for background tasks much easier.
@papr @romanroibu Please make sure to test every dependant of the `PluginTaskManager` that they still work the same way as before:
- `GazeFromOfflineCalibration`
- `Offline_Head_Pose_Tracker`
- `Online_Head_Pose_Tracker`
=> Remove duplicated state logic in PluginTaskManager

pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py, pupil_src/shared_modules/gaze_producer/model/calibration_storage.py, pupil_src/shared_modules/gaze_producer/model/gaze_mapper_storage.py, pupil_src/shared_modules/gaze_producer/model/reference_location_storage.py, pupil_src/shared_modules/storage.py, pupil_src/shared_modules/video_overlay/controllers/overlay_manager.py, pupil_src/shared_modules/video_overlay/plugins/generic_overlay.py
This is a pure refactoring PR, removing the dependency of `Storage` instances on a `Plugin` instance. No existing behavior should change.
**Architectural Reasoning**
There's no reason why a `Storage` should know about the `Plugin` ecosystem or anything else Pupil-related. The only reason for the `Plugin` instances being passed through was to hook into `Plugin.cleanup()` for storing the items in the `Storage` to disk. However, this was not even desired in all cases, as we had a very hacky workaround for changing this logic in `OverlayManager`.
I simply added manual calls to `save_to_disk()` in the appropriate places, imo making it much more obvious what's happening. Of course now you shouldn't forget to make those calls, but then again you have to freedom not to make them if it is not …
=> Remove storage dependency on plugin instances

pupil_src/shared_modules/surface_tracker/surface_file_store.py, pupil_src/shared_modules/surface_tracker/surface_marker_aggregate.py, pupil_src/shared_modules/surface_tracker/surface_serializer.py, pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py, pupil_src/shared_modules/surface_tracker/surface_tracker_online.py
@romanroibu I stumbled upon this by accident. It's actually not in Capture, but a problem with Player.
Player would complain wrongly about deprecated surface definitions when in fact they were not.
Note that most of the diff is applying black.
Take a look at the ~~first~~ second commit.
The `deprecated_definition` is a boolean that can also be `False` when not deprecated.
I wanted to test that this will still correctly warn with deprecated surfaces.
@romanroibu maybe you can help me out here:
I had a recording with both `surface_definitions` and `surface_definitions_v01` and deleted the `_v01` file.
To be sure I also deleted the marker cache.
However with this branch I did **not** get the warning upon opening the modified recording with Player.
I investigated a bit and it seems that the …
=> Fix deprecated surface warning

pupil_src/shared_modules/video_overlay/utils/image_manipulation.py
Fixes #1912 
I added better logging for potential errors here.
Example output for the recording from #1912:
```
player - [DEBUG] video_overlay.utils.image_manipulation: Error rendering 3D eye-ball outline! Skipping...
eye_ball: {'center': (246.79170715146995, 209.36043689754123), 'axes': (-639.8371093372608, -639.8371093372608), 'angle': 90.0}
<class 'cv2.error'>: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/drawing.cpp:1927: error: (-215:Assertion failed) axes.width >= 0 && axes.height >= 0 && thickness <= MAX_THICKNESS && 0 <= shift && shift <= XY_SHIFT in function 'ellipse'
```
=> Prevent crash when rendering eyeball outline with negative values

pupil_src/shared_modules/gaze_producer/controller/calibration_controller.py, pupil_src/shared_modules/gaze_producer/controller/gaze_mapper_controller.py, pupil_src/shared_modules/gaze_producer/controller/reference_location_controllers.py, pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py, pupil_src/shared_modules/tasklib/manager.py
Previously, a user could start multiple background tasks by accident by clicking the `Recalculate` button in the post-hoc calibration UI multiple times. This PR introduces a simple `PluginTaskManager` (previously used) subclass that replaces existing tasks that use a common identifier as the new task. By using the calibration/gaze mapper unique ids as identifiers, there can only be one active task for each calibration/gaze mapper.
=> Introduce UniqueTaskManager to avoid duplicated post-hoc calibration background processes

pupil_src/shared_modules/network_api/controller/frame_publisher_controller.py, pupil_src/shared_modules/network_api/network_api_plugin.py
A restart of the `NetworkAPIPlugin` would cause the frame publishing to stop.
The bug occurred in HMD-Eyes, where the eye preview was not updating when connecting.
This was caused by HMD-Eyes sending a start-plugin notification to ensure that `NetworkAPIPlugin` is running.
Since we allow replacing plugins _by class_ this would result in a restart.
I removed the start/stop logic from the `FramePublisherController`, since it is actually always started.
The `NetworkAPIPlugin` now sends a start notification in `__init__()` which fixes the behavior.
=> Ensure frame publisher restarts when restarting NetworkAPIPlugin

pupil_src/shared_modules/gaze_producer/controller/calculate_all_controller.py, pupil_src/shared_modules/gaze_producer/ui/on_top_menu.py, pupil_src/shared_modules/storage.py
Refactoring PR for clarifying the logic in the `CalculateAllController` for when the reference detection is run and when not.
This PR will be useful for fixing a bug in the control flow for `calculate_all()`.
I think the idea was to abstract away the logic into a single property of the `CalculateAllController`, which the controller and the UI will then query. But the UI actually hooks already into the reference location storage for updating the button text, so we know that this button text is dependent of the storage. Therefore, just querying the storage for both decisions in controller and UI seems to be a clearer solution.
Since we never specify whether a storage needs to have a fixed size, I used the `Iterable` interface to compute whether the storage is empty.
=> Clarify CalculateAllController reference logic

pupil_src/shared_modules/gaze_producer/model/legacy/calibration_storage_updater.py, pupil_src/shared_modules/vis_watermark.py
On some occasions, macOS stores file attributes in meta files that use `._` as prefix. These are matched in cases were we use glob with a pattern starting with `*`.
This PR excludes files starting with `.` to avoid matching the meta files and causing issues down the line.
All other use cases of glob in the project either exclude `.`-prefixed files already or use a concrete prefix which avoids matching meta files.
=> Ignore macOS-specific meta files when using glob

pupil_src/shared_modules/gaze_producer/controller/calculate_all_controller.py, pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py
`calculate_all()` is called on button press and also when pupil data changes.
We don't want to run reference location detection in any automatic workflow since it can take quite a while and consumes a lot of resources.
=> Detect reference locations only on button press

pupil_src/shared_modules/pupil_detector_plugins/visualizer_2d.py, pupil_src/shared_modules/video_overlay/utils/image_manipulation.py
Improves #1947 
- `NaN` data can occur when the eye model is not fitted yet, we don't want to log anything when confidence is zero.
- Same logging behavior added to capture workflow
=> Consistent draw ellipse errors

pupil_src/shared_modules/accuracy_visualizer.py, pupil_src/shared_modules/gaze_mapping/__init__.py, pupil_src/shared_modules/gaze_producer/model/calibration_storage.py, pupil_src/shared_modules/gaze_producer/ui/calibration_menu.py, pupil_src/shared_modules/gaze_producer/worker/create_calibration.py, pupil_src/shared_modules/gaze_producer/worker/map_gaze.py, pupil_src/shared_modules/gaze_producer/worker/validate_gaze.py
Prevent calibrations with unavailable gazers classes (custom gazer classes, `GazerHMD3D`) from being added to `CalibrationStorage`.
=> Prevent calibrations with unavailable gazers from being added

.travis.yml
I added a quick job for checking the codebase with black. I ignored the tests folder as I remember we agreed at some point that black is not very readable with the `assert` statements that you commonly see in pytest. This seems to be a common issue and workaround.
As you can see, there's already a couple of files not being blacked.
I'd probably create a separate PR for fixing those.
=> Automated black checks on travis

pupil_src/shared_modules/gl_utils/utils.py
`glOrtho` does not allow zero-width dimensions. Users of Coord_System should not have to care about this implementation detail. Therefore, Coord_system replaces the zero-width dimensions appropriately to avoid an error down the line.
This fixes an issue with pupil producer timelines who do not span a sufficiently large coordinate system due to an insufficient amount of data.
=> Coord_System: Avoid zero-width dimensions

pupil_src/shared_modules/gaze_producer/ui/calibration_menu.py, pupil_src/shared_modules/gaze_producer/ui/storage_edit_menu.py
Fixes part of the issue described in #1918:
When hitting the **Delete** button multiple times when the UI is blocked, Player would crash on resume.
On current develop it will not crash anymore, but display `Error: Cannot delete calibrations from other recordings!`, which is also wrong.
This happens on Windows (maybe on macOS, too?), but not on Linux.
The reason is that spawning processes on Windows takes so long that the UI freezes for a second, which is enough time to double-click the delete button.
I caught the case in the base UI for completeness but needed to handle it also in the calibration UI because this is where the wrong error message would be thrown.
=> Fix double item deletion crash

pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_hmd.py
Eye translations are only required for fitting/calibrating. If the gazer is used purely for mapping gaze, the eye translations are not necessary. This PR allows the usage of recorded hmd calibrations in Pupil Player.
=> Allow GazerHMD3D to be initialised without eye translations

pupil_src/launchables/service.py
We already have this check in Capture, I just copied it over.
=> Gracefully hande start-plugin requests for non-existing plugins in service

pupil_src/shared_modules/gaze_mapping/gazer_base.py, pupil_src/shared_modules/gaze_mapping/utils.py
=> Prevent Capture from crashing during calibration when there is no reference data 

docs/dependencies-ubuntu17.md
The latest upstream version of ceres is not compatible with C++11 anymore and needs to be compiled with C++14.
We need ceres for building the pupil-detectors library, who's build-pipeline currently uses C++11 exclusively.
Therefore pupil-detectors won't compile with the headers from the latest ceres.
An easy temporary workaround is to build ceres from the last version that supported C++11: v1.14
=> Use ceres version 1.14 before port to C++14

docs/dependencies-ubuntu17.md, docs/dependencies-ubuntu18.md
We noticed that the same bug occurs also in Ubuntu 18 and 20.
Replacing the libusb shared library still fixes the issue.
I added a note for how to determine the location of the system-installed libusb version.
=> Improve Linux libusb fix instructions and add to Ubuntu 18 docs

pupil_src/launchables/world.py
glfwSetWindowSize triggers a frame buffer change which will call on_resize with appropriate parameters.
This fixes an issue on Mac retina displays which caused the world window to flicker after clicking the "Reset window size" button as on_resize() was not called with the window frame buffer size but with the window size. On retina displays, these are different which cause the issue to appear.
=> Remove unnecessary on_resize call

pupil_src/shared_modules/accuracy_visualizer.py
This PR fixes the issue when calculating gaze accuracy, the `Accuracy Visualizer` would report `Angular Accuracy` or `Angular Precision` with a confusing `nan` value. This can happen, for example, when there is no data within the `Outlier Threshold`.
Now, instead of `nan`, the visualizer will report that the value is `Not available`.
=> Gracefully handle accuracy NaN values

pupil_src/launchables/world.py
The function was renamed, the comment wasn't.
=> Fix comment rot, pointing to renamed function

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py
Fixes #1977 
The problem is that pyglui will not ensure a consistent UI when setting the ui-configuration from the session settings.
If the menubar was expanded previously with a plugin that is now not loaded (e.g. because it is not session persistent), the menubar will still be expanded without any plugin selected. We can ensure this consistency manually after restoring the session settings.
I have tested this in Capture and Player with the following custom plugin. I have _not_ tested this in the eye-process, as this is not so easy. But the code should work as well in case we ever have a non-session-persistent eye plugin.
```python
from plugin import Plugin
from pyglui import ui
class MenubarCollapseTestPlugin(Plugin):
def init_ui(self):
self.add_menu()
self.menu.label = …
```
=> Ensure collapsed menubar for unloaded previously selected plugins

pupil_src/shared_modules/zmq_tools.py
Previously, the zmq log handler's exception handling expected the "msg" field to be a string. If an object is passed that is not msgpack-serializable, the exeception handling will fail, e.g logger.debug([uuid.uuid4()]). This PR solves this issue by converting the "msg" field to a string in case of an initial serialization failure.
=> Fix serialization issue in zmq log handler

pupil_src/shared_modules/gaze_mapping/gazer_2d.py
Currently, the 2D gazer crashes if not all models are fit successfully, e.g. during monocular calibrations. In these cases, access to the model parameters fails. This PR checks if a model was fit successfully before attempting to access the model parameters.
Issue traceback:
```py
File "launchables/world.py", line 642, in world
File "launchables/world.py", line 409, in handle_notifications
File "shared_modules/plugin.py", line 391, in add
File "shared_modules/gaze_mapping/gazer_base.py", line 226, in __init__
File "shared_modules/gaze_mapping/gazer_base.py", line 245, in get_params
File "shared_modules/gaze_mapping/gazer_2d.py", line 54, in get_params
AttributeError: 'LinearRegression' object has no attribute 'coef_'
```
=> Fix crash when calibrating 2D monocularly

pupil_src/launchables/player.py, pupil_src/shared_modules/gaze_producer/ui/calibration_menu.py, pupil_src/shared_modules/gaze_producer/ui/storage_edit_menu.py
This PR ensures that the `Duplicate` and `Delete` buttons in Post-hoc Calibration menu are disabled, if those actions are not available and would generate an error log. This happens when the calibration is from a different recording, or the calibration is pre-recorded.
EDIT: Requires https://github.com/pupil-labs/pyglui/releases/tag/v1.28 or later
=> Disable read only buttons in post-hoc calibration menu

pupil_src/launchables/eye.py
Using #1976 as the target as this PR is branched of it. Can be changed to `develop` once it is reviewed.
Changes:
- **Use 192x192 as the preferred frame size explicitly** - Previously, 192x192 was chosen implicitly for Pupil Cam2 and Cam3 as the UVC backend will fallback to the closest frame size if the preferred frame size is not available.
-  **Set 500x500 as default content area** - Pupil Cam1 uses 4:3 resolutions. Pupil Cam2 and Cam3 use 1:1 resolutions. As all Pupil Core and VR/AR add-ons are shipped with Pupil Cam2 and Cam3 cameras, we adjust the default eye window size to a 1:1 content aspect ratio. The size of 500 was chosen s.t. the menu still fits.
@pfaion Please test with different scaling options on
---
=> Eye window: Set 500x500 as default content size

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/service_ui.py
This PR removes the GUI user scale feature as it was only intended to compensate for high-DPI displays.
With the latest merge of #1976 Pupil can handle high-DPI displays natively across all platforms, so we don't need this feature anymore.
=> Remove gui user scale

docs/dependencies-windows.md
You will need git to run Pupil from source, so we should add it to the setup docs.
=> Add notes about installing git to Windows docs

pupil_src/shared_modules/camera_models.py, pupil_src/shared_modules/pupil_recording/update/old_style.py, pupil_src/shared_modules/pupil_recording/update/update_utils.py, pupil_src/shared_modules/video_capture/__init__.py, pupil_src/shared_modules/video_capture/file_backend.py, pupil_src/shared_modules/video_capture/ndsi_backend.py, pupil_src/shared_modules/video_capture/uvc_backend.py
This is a refactoring PR, cleaning up the code and logic used in camera_models.py.
It will make it easier to integrate eye camera intrinsics for correct usage of the focal length in the 3D detector later on.
Summary of changes:
1. Moved all duplicated code between the radial and fish-eye camera into the existing base class
2. Used a factory pattern and proper base-class registration for file (de)serialization of camera models.
It seems that there also was some bug caused by the previous logic, but it did not have any visible effect:
Saved dummy intrinsics would be loaded as a radial camera model instead of the dummy camera model.
3. I reworded all uses of "calibration" referring to intrinsics to "intrinsics". Also fixed inconsistent usage of "pre-recorded", sometimes meaning "included in …
=> Cleanup camera models

pupil_src/shared_modules/pupil_recording/update/invisible.py, pupil_src/shared_modules/video_capture/utils.py
This PR adds support for integrating the output of the headset on/off classifier data into gaze data confidence for Pupil Invisible recordings. Previously, the confidence of gaze data for such recordings was always set to `1.0`. The new implementation sets the confidence to `0.0` if the classifier output for the given gaze datum is `0` (which means `off`), or `1.0` if the output is `255` (`on`). If the classifier data file is missing, the implementation falls back to the old implementation of setting the confidence to `1.0`.
=> Support PI headset on/off classifier data

pupil_src/shared_modules/gaze_producer/controller/gaze_mapper_controller.py, pupil_src/shared_modules/gaze_producer/ui/gaze_mapper_menu.py, pupil_src/shared_modules/gaze_producer/ui/gaze_mapper_timeline.py
This PR fixes an issue where changing the calibration in post-hoc gaze mapping would not update the timeline to reflect the calibration's range.
---
1. Make a Capture recording including at least one calibration
1. Open recording in Player
1. Select post-hoc gaze calibration
1. At least one calibration should show up as "Recorded Calibration"
1. The "default gaze mapper" has "Recorded Calibration" selected as calibration
1. Create a new "Default Calibration"
1. Change calibration range to something else than the complete recording
1. In the "default gaze mapper" select "default calibration" as calibration
- [!!!] At this point the calibration range timeline should update to the corresponding range
1. Changing the calibration range again correctly updates the visualisation
=> Fix post-hoc calibration timeline update

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/service.py, pupil_src/launchables/world.py, pupil_src/shared_modules/audio_playback.py, pupil_src/shared_modules/os_utils.py, pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py, pupil_src/shared_modules/pupil_recording/__init__.py, pupil_src/shared_modules/pupil_recording/info/__init__.py, pupil_src/shared_modules/pupil_recording/info/recording_info.py, pupil_src/shared_modules/pupil_recording/info/recording_info_2_0.py, pupil_src/shared_modules/pupil_recording/info/recording_info_2_1.py, pupil_src/shared_modules/pupil_recording/info/recording_info_2_2.py, pupil_src/shared_modules/pupil_recording/info/recording_info_utils.py, pupil_src/shared_modules/pupil_recording/update/invisible.py, pupil_src/shared_modules/pupil_recording/update/mobile.py, pupil_src/shared_modules/pupil_recording/update/new_style.py, pupil_src/shared_modules/pupil_recording/update/old_style.py, pupil_src/shared_modules/recorder.py, pupil_src/shared_modules/version_utils.py, pupil_src/shared_modules/video_capture/ndsi_backend.py, pupil_src/shared_modules/video_capture/uvc_backend.py
This PR ensures all comparisons of version numbers are done with parsed version strings, and using the best practices.
=> Better version comparison

pupil_src/shared_modules/camera_intrinsics_estimation.py, pupil_src/shared_modules/camera_models.py, pupil_src/shared_modules/video_capture/hmd_streaming.py
This fixes a bug where loading dummy intrinsics from file would crash because the `Dummy_Camera` constructor does not consistently overwrite the parent constructor. I moved name and resolution to the start from for all constructors as these are the least likely to change and adjusted the `Dummy_Camera` constructor to be consistent with the others.
This bug surfaced now after #1992 where I fixed that saved dummy intrinsics would always be loaded via the radial camera model instead of the dummy camera model (therefore the dummy constructor was never used when loading from file).
=> Fix camera model loading

pupil_src/shared_modules/observable.py, pupil_src/tests/test_observable.py
@papr please add more reviewers as you see fit.
- Currently, the wrapper stores a reference to the wrapped function causing a reference cycle. This prevents garbage collection by reference counting. This is fixed by using a weakref to the object and referencing only the unbound method.
- I added test cases that test if wrapped methods still work before being wrapped (this is not related to the changed wrapper, these should have already been tested in the previous version)
- Use f-strings instead of `format` because we require Python >=3.6
- Add a descriptor for wrapped methods that prevents them from being replaced
I tested the code with python 3.6.10 and 3.8.2
=> Improve Observable

pupil_src/launchables/eye.py, pupil_src/shared_modules/camera_models.py, pupil_src/shared_modules/plugin.py, pupil_src/shared_modules/pupil_detector_plugins/detector_3d_plugin.py, pupil_src/shared_modules/pupil_recording/info/__init__.py, pupil_src/shared_modules/pupil_recording/info/recording_info_2_3.py, pupil_src/shared_modules/pupil_recording/update/new_style.py, pupil_src/shared_modules/pupil_recording/update/update_utils.py
This PR uses the eye camera intrinsics (specifically focal_length) to get a more accurate 3D eyeball position estimate.
Depends on [pupil-detectors](https://github.com/pupil-labs/pupil-detectors) v1.1.1, upgrade with
```
pip install -U pupil-detectors
```
**Summary**
- Added known intrinsics for the eye cameras to camera_models.py
- On recording stop, current eye camera intrinsics are saved to the recording (like with world.intrinsics)
- The 3D detector is initialized with `g_pool.capture.intrinsics.focal_length` (cannot be changed at runtime)
- On focal_length changes (e.g. by changing the resolution), the 3D detector and all dependent UI is re-initialized
- Added clear warnings that loading dummy intrinsics is not good
- Added upgrade mechanism (RecordingInfo v2.3) which creates …
=> Pass eye camera focal_length to 3D detector

pupil_src/shared_modules/recorder.py
This PR fixes a crash on starting a recording. The code was using an attribute from the old `Version` class that was recently replaced.
=> Fix recorder crash on version formatting

pupil_src/shared_modules/pupil_detector_plugins/visualizer_2d.py
TLDR: the missing `return` would cause a crash later on.
There was a new error type that could happen here, so I extended the logging and comments as well. Additionally, the previous error handling was not correct, as we would still crash when running the code below without `pts` being computed.
=> Prevent eye window crash from ellipse2Poly issues

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/gl_utils/__init__.py, pupil_src/shared_modules/gl_utils/window_position_manager.py, pupil_src/shared_modules/glfw.py, pupil_src/shared_modules/service_ui.py
This PR fixes issues related to windows being outside the display bounds when recovering a session.
=> Ensure windows are visible when recovering a session

docs/dependencies-ubuntu17.md, docs/dependencies-ubuntu18.md
GLFW 3.3 is not available via `apt` on Ubuntu < 20.04, so you need to build it manually on 17.10 or 18.04.
Added build instructions to the docs and removed `libglfw-3` from the `apt` commands.
PR to master as this is docs related.
=> Add build instructions for glfw-3.3 to ubuntu docs

pupil_src/shared_modules/pupil_recording/recording.py, pupil_src/shared_modules/video_overlay/plugins/eye_overlay.py, pupil_src/shared_modules/video_overlay/utils/image_manipulation.py
This PR fixes issues related to the eye overlay plugin that caused crashes when the confidence value was not valid (`inf` or `nan`). Additionally, it fixes the way this plugin was searching for eye videos in the recordings and was causing it to mistakenly use `eye1.instrinsics` as a video source.
---
[Click-Up Task](https://app.clickup.com/t/8jxww7)
=> Fix eye overlay plugin video file filter

pupil_src/shared_modules/video_capture/utils.py
In recordings previous to #1573, it is possible that recordings include zero-valued timestamps. As a workaround, we introduced #1551. This PR fixes an edge case of this workaround. If the last timestamp is zero, `timestamps[invalid_idc + 2]` causes an index error. As a fix, we handle this edge case separately.
=> Fix an edge case in _fix_negative_time_jumps() when the last TS is zero

pupil_src/shared_modules/observable.py, pupil_src/tests/test_observable.py
This PR allows to observe monkey patched methods (you replace or modify method attributes of a class instance s.t. methods are called that were not in the original class definition).
Additionally, the error when trying to add private methods as observers was made a little more explicit.
=> Allow observing of monkey patched methods

pupil_src/shared_modules/pupil_detector_plugins/pye3d_plugin.py, pupil_src/shared_modules/pupil_detector_plugins/visualizer_pye3d.py
This modifies the Pye3D plugin to be compatible with the latest changes on the Pye3D repository.
Specifically, this was tested with https://github.com/pupil-labs/pye3d-detector/commit/71f8c4fae7463c6d31b1f8f6473aa033f11a664c which is as of now the latest master.
Besides adjusting for the new API, this PR also takes care of resetting the detector if the intrinsics change.
=> Support for Pye3D rework

docs/dependencies-windows.md
The window's build binary service, zeranoe, was shut down and a replacement was needed. This is in reference  to issue #2016
=> updated the build binary link in documenation

pupil_src/launchables/eye.py, pupil_src/launchables/world.py
This PR fixes an issue on macOS that caused FPS drops when the window becomes occluded.
---
[ClickUp Task](https://app.clickup.com/t/7cnn4h)
=> Fix FPS drop on macOS for occluded windows

pupil_src/shared_modules/video_capture/utils.py
Fixes regression in #2026 where `_fix_negative_time_jumps()` would crash with an index error if no invalid_idc were found.
ts =timestamps
=> TS Lookup Table: Return unmodified ts if no invalid ts were found

pupil_src/shared_modules/surface_tracker/offline_utils.py, pupil_src/shared_modules/surface_tracker/surface_marker_detector.py, pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
- Fixes #1806 
- Fixes inverted legacy marker detection
- Tries to set detector configuration based on cache, else false back to session settings
=> Surface tracker stability improvements

docs/dependencies-macos.md, docs/dependencies-ubuntu17.md, docs/dependencies-ubuntu18.md, docs/dependencies-windows.md, requirements.txt
This PR extracts Python dependencies from the documentation file, and puts them into `requirements.txt` such that it can be used with `pip`.
Tested:
- ✅  Windows
- ✅  Ubuntu
- ✅  macOS
Todo:
---
[ClickUp](https://app.clickup.com/t/7cvqe3)
=> Add requirements.txt file

.travis.yml
[Travis automatically runs `pip install -r requirements.txt` if such a file is present.](https://docs.travis-ci.com/user/languages/python/#dependency-management). Since we do not need the requirements to be installed, we need to explicitly overwrite the `install` command.
=> Fix Travis black tests

pupil_src/launchables/eye.py
I noticed that the CPU graph is being updated too often on my setup, resulting in non-readable UI, not sure if it is the general case.
I also noticed that this too frequent refresh is using a good chunk of CPU in the eye process.
This small PR makes the CPU graph to be updated at the screen refresh rate, but I am not sure this is the optimal choice.
WDYT?
=> fix cpu graph refresh, improve performance and UI look

pupil_src/launchables/eye.py
Just made a minor change to avoid calling `glfw.window_should_close` in the main event-loop, but rather in the screen-updating-loop at a lower rate. I noticed while profiling that these accumulated calls uses a significant amount of CPU time in comparison to the rest (~7%). It seems to me that checking if the window should be closed at a frequency higher than screen refresh is not necessary.
(PS: I am trying to deal with a GigEVision camera with high-framerate (250+fps) and 640x480 resolution, trying to dump the video for recording, so I am really trying to save as many CPU cycles as possible. I do not have the regular pupil headset, so I cannot check if that occurs in the more regular setting.)
=> reduce calls to glfw.window_should_close to screen fps for performance

.travis.yml, deployment/deploy_capture/version.py, deployment/deploy_player/version.py, deployment/deploy_service/version.py, pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/gl_utils/__init__.py, pupil_src/shared_modules/gl_utils/trackball.py, pupil_src/shared_modules/gl_utils/utils.py, pupil_src/shared_modules/marker_auto_trim_marks.py, pupil_src/shared_modules/math_helper/__init__.py, pupil_src/shared_modules/pupil_detector_plugins/visualizer_3d.py, pupil_src/shared_modules/pupil_detector_plugins/visualizer_pye3d.py, pupil_src/shared_modules/service_ui.py, pupil_src/shared_modules/visualizer.py
Removed from module import * as mentioned in issue #1986. 
If this merge is without any bugs this can be further improved by removing:
- deployment/deploy_capture/version.py
- deployment/deploy_player/version.py
- deployment/deploy_service/version.py
since these are only used to import pupil_src/shared_modules/version_utils.py to different location
=> remove from module import *

pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_headset.py
In order to estimate the `gaze_point_3d`, we calculate the nearest intersection between the `gaze_normal`s. If these are nearly parallel and there is some noise, it is possible that the estimate is actually behind the scene camera. Until now, this case has not been explicitly been handled.
Unfortunately, when using the fixation detector with `gaze_point_3d` input, it is possible that such an estimate breaks a larger fixation into multiple smaller ones. 
Hmd-eyes has been handling this case [by flipping the `gaze_point_3d`](https://github.com/pupil-labs/hmd-eyes/blob/master/plugin/Scripts/GazeData.cs#L182-L187) in case it lies behind the camera.
With this PR, we start applying this flipping strategy directly in the gazer, before publishing the gaze data.
=> Flip gaze with negative z-component

pupil_src/shared_modules/pupil_detector_plugins/pye3d_plugin.py
As there will be backward-incompatible changes to https://github.com/pupil-labs/pye3d-detector/, we pin the supported version to the current version to avoid any future issues.
=> pye3d_plugin: Support specific pye3d version 0.0.1 only

pupil_src/shared_modules/gl_utils/trackball.py
Issue reported on [Discord](https://discord.com/channels/285728493612957698/285728493612957698/775366466496888839).
Traceback provided via email
```py
2020-11-09 10:01:22,385 - eye0 - [ERROR] launchables.eye: Process Eye0 crashed with trace:
File "launchables\eye.py", line 731, in eye
File "site-packages\glfw\__init__.py", line 1772, in poll_events
File "site-packages\glfw\__init__.py", line 632, in errcheck
File "site-packages\glfw\__init__.py", line 54, in _reraise
File "site-packages\glfw\__init__.py", line 611, in callback_wrapper
File "shared_modules\pupil_detector_plugins\visualizer_3d.py", line 290, in on_resize
File "shared_modules\gl_utils\trackball.py", line 57, in set_window_size
ZeroDivisionError: float division by zero
```
- Cause: On …
=> Fix minimizing 3d detector debug window on Windows OS

pupil_src/shared_modules/video_capture/uvc_backend.py
Affected process: `world`
Used patterns for camera auto selection: `["ID2", "Logitech"]`
Matched cameras were only sorted by bus number. This PR introduces priority based on the matched pattern order. Bus number is used as secondary sort key.
=> Fix UVC camera auto-selection in case of multiple pattern matches

pupil_src/shared_modules/pupil_recording/update/invisible.py
This new recording format has been introduced in Pupil Companion 1.0.0.
This version provides support for the OnePus 8 and Android 11.
On the OnePlus 8, eye videos will be h264-encoded which is why a
recording format bump was necessary. Pupil Player is already able to handle
these. Therefore, a simple version bump is necessary to support the new
recording format.
=> Support Pupil Invisible recording format v1.4

pupil_src/shared_modules/video_capture/hmd_streaming.py
Forwards an HWM argument from HMD_Streaming_Source to Msg_Receiver (which has a hmw=None argument already).
=> HMD Streaming: Support custom receiver high-water mark and set default value from None to 1

pupil_src/launchables/eye.py
Currently, if the eye process crashes due to a faulty plugin, the window will remain opened, but unresponsive (at least on macOS).
This PR will close the window and terminate glfw even if an error occurs, effectively closing the window in any case.
=> Close eye window on crash

pupil_src/shared_modules/raw_data_exporter.py
pye3d no longer includes this field. Previously, this would result
in all 3d outputs being empty. This PR changes continues to export
all 3d fields, even if this one is not present.
=> Make model_id optional for pupil 3d raw data export

pupil_src/shared_modules/pupil_producers.py
[ClickUp Task](https://app.clickup.com/t/apxpbc)
=> Fix post hoc pupil detection progress for zero total frames

pupil_src/launchables/eye.py, pupil_src/main.py
Until there is no way for the eye process to detect if it runs
within Pupil Capture, Player, or Service. This PR passes this info
explicitly to the process which stores it in `g_pool.app`
=> main: Pass parent_application to eye process

docs/dependencies-windows.md, pupil_src/main.py
The code states that the launcher process should react to ` launcher_process.should_stop` though it seems not to be the case :
https://github.com/pupil-labs/pupil/blob/af660c38447cc6b199bd3eda292f4e4c769a0147/pupil_src/main.py#L124 
It assumes that closing children processes will lead to the launcher process exit.
Wrote that quickly, so would need feedback on implementation.
Thanks
=> add missing launcher_process.should_stop handling

pupil_src/shared_modules/pupil_recording/update/update_utils.py
Zero-byte files do not trigger an AVError when attempting to open them. Their `format` is `None` which causes an `AttributeError` down the line. This PR handles these files as if they were broken containers (which they are effectively).
=> Handle zero-byte video files when looking up Pupil Mobile intrinsics

pupil_src/shared_modules/video_capture/utils.py
This PR adds support for 200Hz gaze data in Pupil Invisible recordings. The recording upgrade procedure will prioritise 200Hz data, if it's available, and fall back to the old behaviour in case it's not available.
=> Support 200hz gaze data in PI recording

pupil_src/shared_modules/pupil_recording/update/invisible.py
This PR adds to the [fix for PI with broken video](https://github.com/pupil-labs/pupil/pull/2077).
=> Gracefully handle PI recordings with broken video #2

deployment/bundle_macos.sh, deployment/deploy_capture/bundle.spec, deployment/deploy_player/bundle.spec, deployment/deploy_service/bundle.spec, deployment/find_opengl_bigsur.py
Closes  #2079
TODO: a349031 is to be reverted once pyinstaller/pyinstaller#5491 is fixed.
=> macOS 11 Big Sur bundle compatibility

pupil_src/launchables/player.py, pupil_src/shared_modules/audio_playback.py, pupil_src/shared_modules/blink_detection.py, pupil_src/shared_modules/fixation_detector.py, pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py, pupil_src/shared_modules/gaze_producer/gaze_from_recording.py, pupil_src/shared_modules/gaze_producer/gaze_producer_base.py, pupil_src/shared_modules/plugin.py, pupil_src/shared_modules/plugin_manager.py, pupil_src/shared_modules/pupil_producers.py, pupil_src/shared_modules/pupil_recording/__init__.py, pupil_src/shared_modules/pupil_recording/info/__init__.py
This PR makes some Pupuil Player plugins explicitly unavailable, depending on the software used to create the recording.
| Player Plugin | Pupil Invisible | Pupil Mobile |
| :-- | :-: | :-: |
| Blink detection | `unavailable ` | - |
| Fixation detection | `unavailable ` | - |
| Post-hoc pupil detection | `unavailable ` | - |
| Post-hoc gaze calibration | `unavailable ` | - |
| Pupil from recording | - | `unavailable ` |
| Gaze from recording | - | `unavailable ` |
---
---
[ClickUp Task](https://app.clickup.com/t/cpw1mg)
=> Custom Pupil Player plugin list for Invisible/Mobile recordings

pupil_src/shared_modules/audio_playback.py, pupil_src/shared_modules/audio_utils.py, pupil_src/shared_modules/av_writer.py, pupil_src/shared_modules/methods.py, pupil_src/shared_modules/video_capture/file_backend.py
Ignores audio and video decoding issues in the middle of the stream. (Decoding issues at the start of the stream disables the audio/video stream as it assumes the complete stream to be broken.)
Previously, the software crashed when encountering such decoding issues. The new implementation can lead to audio desync or silence when encountering any audio decoding issues. This is assumed to be an acceptable trade-off given the previous behavior.
=> Support recordings with decoding issues

pupil_src/shared_modules/audio_playback.py
---
[ClickUp Task](https://app.clickup.com/t/euy6a8)
=> Workaround for Player crashing with OSError: [Errno -9986] Internal PortAudio error

pupil_src/shared_modules/annotations.py
This PR changes the default annotation hotkey from "E" to "a". This is to make it harder to accidentally trigger an export ("e" hotkey).
[ClickUp Task](https://app.clickup.com/t/gb1rv9)
=> Update default annotation hotkey

pupil_src/shared_modules/pupil_groups.py
After changing to msgpack 1.0, the `encoding="utf-8"` argument has been removed, causing an exception on use. We were ignoring this, causing this issue to stay undetected for a while.
I also made the use of msgpack more explicit.
=> Fix msgpack unpack in Pupil Groups

pupil_src/launchables/player.py, pupil_src/shared_modules/pupil_producers.py, pupil_src/shared_modules/raw_data_exporter.py
This PR removes the `"Pupil from Recording"` pupil data option from Player for Pupil Invisible recordings. These recordings don't contain any pupil data, so this PR is only meant to provide consistency in the way Player works. This PR also prevents raw data exports from generating an empty `pupil_positions.csv` when no pupil data is available.
---
[ClickUp Task](https://app.clickup.com/t/fh1cqd)
=> Disable "Pupil from Recording" for Pupil Invisible recordings

pupil_src/launchables/world.py, pupil_src/shared_modules/hololens_relay.py
This PR fixes a bug that prevented toggling pupil detection on/off in Capture's general settings.
---
[ClickUp Task](https://app.clickup.com/t/d733te)
=> Fix toggling pupil detection on/off

pupil_src/shared_modules/plugin.py
This PR fixes an issue where a new video source in the eye process wouldn't completely replace the previous one.
---
[ClickUp](https://app.clickup.com/t/gh73dm)
=> Deinit UI when cleaning plugin list for eye processes

pupil_src/shared_modules/pupil_recording/info/recording_info_utils.py, pupil_src/shared_modules/pupil_recording/update/invisible.py
This PR fixes an issue where a less precise version of start time was used when rewriting timestamps as part of the update procedure for Pupil Invisible recordings.
---
[ClickUp Task](https://app.clickup.com/t/h18pw0)
=> Fix Pupil Invisible rewrite timestamps

pupil_src/shared_modules/pupil_detector_plugins/pye3d_plugin.py
This PR changes the colors in pye3d debug window to make them consistent with pupil and eye outlines.
---
[ClickUp Task](https://app.clickup.com/t/gv5r7u)
=> Make pye3d plugin colors consistent

pupil_src/shared_modules/log_history.py, pupil_src/shared_modules/pupil_recording/info/recording_info_utils.py
> If encoding is not specified, the default is platform dependent (see open())
https://docs.python.org/3/tutorial/inputoutput.html
This can lead to problems when reading files that were generated on different platforms and contain characters that are incompatible with the default encoding, e.g. info.json file recorded by Pupil Invisible Companion.
This PR uses utf-8 to decode all text-files that are guaranteed to be utf-8 encoded (log file and Pupil Invisible Companion info files).
For all other recordings, it is not possible to assume the utf-8 encoding. Should one encounter `UnicodeDecodingError`s when opening recordings in Player, once can start Player with the `-X UTF-8` flag to enforce utf-8 decoding everywhere.
=> Decode text files using utf-8 encoding explicitly for files that are guaranteed to be utf-8 encoded

pupil_src/shared_modules/surface_tracker/background_tasks.py, pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
---
[ClickUp Task](https://app.clickup.com/t/m76rbd)
=> Prevent incomplete/invalid surface tracker exports

pupil_src/shared_modules/player_methods.py, pupil_src/shared_modules/pupil_recording/update/old_style.py
In [v1.16](https://github.com/pupil-labs/pupil/releases/v1.16), recordings made with
- Pupil Capture `v1.2` or earlier, and
- Pupil Mobile `r0.22.x` or earlier
have been deprecated due to the fact that these recordings are missing meta information that is required for the upgrade to the `Pupil Player Recording Format 2.0`. For details see "Missing Meta Information" in the [v1.16 release notes](https://github.com/pupil-labs/pupil/releases/v1.16).
In order to make users aware of this, upgrading such recordings was only possible through the use of v1.16 and v1.17. Due to a bug, this was no longer possible for all kind of recordings. In addition, users running macOS Big Sur are no longer able upgrade such recordings as the earliest version running on macOS Big Sur is Pupil Player v3.1. …
=> Support upgrading legacy recordings

deployment/generate_msi_installer.py
Pupil Core software is installed to `C:\Program Files (x86)\Pupil-Labs` by default. This directory should be accessible by all users but the start menu entry and desktop shortcut are only installed for the current user. With this PR, future MSI installers will create start menu entries and desktop shortcuts for all users on install.
=> Windows: Create start menu entries and desktop shortcuts for all users on install

pupil_src/shared_modules/av_writer.py, pupil_src/shared_modules/video_export/plugin_base/isolated_frame_exporter.py, pupil_src/shared_modules/video_export/plugins/world_video_exporter.py
Exporting video can take a long time. Pupil Player writes the result incrementally to disk. Specifically, it writes the result directly to the final export location. While the export is ongoing, the video file is invalid but still available to the user. This can lead to users opening the video before it has finished exporting and then encountering playback issues.
This PR changes the video exports to include a `.writing` file name suffix during the export. This prevents other applications from recognizing the partially exported video file as complete. Once the export is done, the suffix is removed and other applications are able to recognize the file type as video.
=> Export-in-progress file-name suffixes

pupil_src/shared_modules/recorder.py
Add UI toggle to Recorder menu to disable scene/world video recording in Pupil Capture. Recording scene video remains the default behavior.
=>  Make scene video recording optional 

pupil_src/shared_modules/annotations.py, pupil_src/tests/annotations/test_annotation_deserialization.py
Starting with this PR, annotation definitions are stored in `<recording dir>/offline_data/annotation_definitions.json` with the format
```json
{
"version": 1,
"definitions": {
"<label>": "<hotkey>"
}
}
```
This file can be shared between recordings.
On load, Pupil Player attempts to load the annotation definitions from the recording-specific file. If it is not found or invalid, it will fallback to the session settings, i.e. the last known annotation definitions.
=> Recording-specific hotkeys

pupil_src/shared_modules/zmq_tools.py
Prior to this commit/PR, using logging.exception would cause an error when reconstructing the traceback in the main log handler. Since the traceback cannot be transferred via msgpack, this commit/PR formats the traceback before sending it over the IPC to the main log handler.
=> Support logging.exception

pupil_src/shared_modules/surface_tracker/surface_tracker.py
These two homographies are necessary to transform points from the [surface coordinate system](https://docs.pupil-labs.com/core/terminology/#surface-aoi-coordinate-system) to the [2d image space](https://docs.pupil-labs.com/core/terminology/#coordinate-system) of the scene camera, and vice versa. They have been available as part of the surface location exports in Pupil Player. With this PR, they also become available to other plugins in Pupil Capture or via its Network API.
=> Add `surf_to_dist_img_trans` and `dist_img_to_surf_trans` to surface events

pupil_src/shared_modules/head_pose_tracker/worker/export_worker.py
Simple typo fix in the exported files
=> Fixing typo in exported headpose files

pupil_src/shared_modules/recorder.py
Follow up PR for #2167
- Fixes crash below
- Demotes "No world video recorded" log message from `error` to `warning`
Crash if no world camera is connected during recording:
```py
world - [ERROR] launchables.world: Process Capture crashed with trace
File ".../pupil/pupil_src/launchables/world.py", line 741, in world
p.on_notify(n)
File ".../pupil/pupil_src/shared_modules/recorder.py", line 289, in on_notify
self.stop()
File ".../pupil/pupil_src/shared_modules/recorder.py", line 497, in stop
self.writer.release()
File ".../pupil/pupil_src/shared_modules/av_writer.py", line 243, in release
self.close()
File ".../pupil/pupil_src/shared_modules/av_writer.py", line 234, in close
os.rename(self.output_file_path_in_porgress, output_file_path)
FileNotFoundError: …
```
=> Fix renaming world video file if no file was written

pupil_src/shared_modules/system_graphs.py
Previously, the confidence graphs in Pupil Player had no data for pre-2.0 recordings. This PR fixes this by falling back to the legacy pupil topic.
---
https://app.clickup.com/t/nz7r5x
=> Fix confidence graphs in Pupil Player for pre-2.0 recordings

pupil_src/shared_modules/pupil_recording/update/invisible.py, pupil_src/shared_modules/video_capture/utils.py
When Pupil Player opens a Pupil Invisible recording for the first time, it performs an in-place upgrade procedure due to compatibility reasons. In this process, it loads PI gaze data and generates Pupil Player compatible gaze data based on it. 
Due to a flaw in the previous gaze conversion procedure, Pupil Cloud post-processed 200 Hz gaze data could be loaded multiple times or not at all.
This PR moves the prior implementation from `video_capture.utils` to `pupil_recording.update.invisible` and restructures the code flow such that 200 Hz gaze data is processed separately from the case where gaze data is loaded from the real-time recorded files.
Below a detailed description of what should be happening:
Pupil Invisible Companion records gaze data into three different sets of files. Their …
=> Fix loading 200 Hz gaze data in Pupil Invisible recordings

pupil_src/shared_modules/audio_playback.py, pupil_src/shared_modules/audio_utils.py
Previously, loading very short audio streams would cause the audio resampler to always return None, resulting in crashes due to uninitialized variables. This PR handles this case gracefully.
=> Fix loading short audio streams

pupil_src/launchables/eye.py, pupil_src/launchables/world.py, pupil_src/main.py, pupil_src/shared_modules/launchable_args.py, pupil_src/shared_modules/video_capture/uvc_backend.py
Fixes #2207
Using the `-skip-driv` or `--skip-driver-installation` flags, one can now launch Pupil Capture and Pupil Service without running the automatic driver installation on Windows.
@N-M-T could you please give this PR a try? You should see a debug log message that the driver installation was skipped when using the flags.
=> Add argument to Pupil Capture and Service to skip the automatic driver installation on Windows

pupil_src/shared_modules/raw_data_exporter.py
Pupil Core software assigns "confidence" values to its pupil  detections and gaze estimations. They indicate the quality of the measurement. Until now, the raw data exporter plugin exported all data, independently of its confidence. New users are often not aware of this and wonder why the exported data looks noisier than what they have seen in Pupil Player.
For visualization, Pupil Player hides gaze data below the "Minimum data confidence" threshold (adjustable in the general settings menu). Often, we recommend users to filter their data by a confidence threshold after exporting.
Starting with this PR, users will have the option to only including data  above the "Minimum data confidence" threshold in the export. The option can be enabled in the raw data exporter's menu.
(credits to @N-M-T …
=> Raw data exporter: Add option to not export low confidence values

pupil_src/launchables/player.py, pupil_src/shared_modules/pupil_recording/recording_utils.py
Pupil Player needs to be able to write to a recording directory for multiple reasons, e.g. upgrading recordings, caching results, exporting data, etc. To avoid issues, Pupil Player will check if it has sufficient permissions before opening a recording and warn the user if this is not the case.
Users on macOS Monterey will encounter this issue frequently as they are required to run Pupil Capture with root privileges (https://github.com/libusb/libusb/issues/1014). In these cases, Pupil Player will present the user the option to change the file ownership from `root` to their current user.
This change of ownership only needs to be done once and can be performed alternatively via the terminal using the `sudo chown -R $USER <recording dir>` command.
=> Player: Check for file write permissions when opening a recording

pupil_src/shared_modules/blink_detection.py
If no pupil data is available the calculation can happen very fast and `time.time()` might not have sufficient resolution to measure a time difference > 0. As a result, `tm1 - t0` might equal zero and cause a ZeroDivisionError in the log statement.
Using time.perf_counter should yield sufficient precision to avoid this issue.
Issue reported via [Discord](https://discord.com/channels/285728493612957698/285728493612957698/968845448204939314)
Workaround plugin for Pupil Core software <3.6 can be found [here](https://gist.github.com/papr/c02bf229ac9a94e9fbee633cd53113db).
=> Avoid ZeroDivisionError in post-hoc blink detection

pupil_src/shared_modules/camera_intrinsics_estimation.py
[User plugin for backwards compatible fix](https://gist.github.com/papr/98636456fd4b4d0621835ac0d3cffc77)
----
https://app.clickup.com/t/1vxq751
=> Handle Camera Intrinsics Estimation crash if no circles are detected on Windows

pupil_src/launchables/service.py
The Pupil Service logger log-level was set to the default value (warning) and did not display any info- or debug-level messages. By setting the log-level to `NOTSET`, the handlers get the chance to process every message based on their on level.
=> Fix logging setup in Service

pupil_src/launchables/service.py, pupil_src/shared_modules/service_ui.py, pupil_src/shared_modules/video_capture/neon_backend/plugin.py
Activate the connected Neon device by clicking the button in the UI or by sending the following notification:
```py
{
"subject": "neon_backend.auto_activate",
"scene": False,
"eyes": True,
}
```
=> Add Neon support to Pupil Service

pupil_src/shared_modules/gaze_mapping/__init__.py, pupil_src/shared_modules/gaze_mapping/gazer_3d/__init__.py, pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_headset.py, pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
The 3d calibration assumes an initial translation of the eyeball centers relative to the scene camera. Since Neon has a different scene camera placement relative to the eyes, the result is worse when using the Pupil Core translation values with Neon hardware.
This PR introduces a new gazer class that uses translation values optimized for Neon.
To use it, select `3D Neon` as `Gaze Mapping` method in the `Calibration` menu.
Bundle: https://github.com/pupil-labs/pupil/actions/runs/4135338823
=> Neon-specific 3d calibration parameters

pupil_src/launchables/eye.py, pupil_src/launchables/player.py, pupil_src/launchables/world.py, pupil_src/shared_modules/gl_utils/__init__.py, pupil_src/shared_modules/gl_utils/utils.py, pupil_src/shared_modules/service_ui.py
We had a curious issue for years where eye or world window would freeze on our production setup only. However moving the mouse over the frozen window would usually unfreeze it. The main issue was data loss, because the software was not processing camera frames and the network buffers would overflow.
After inspecting the stack when that freezing occurs, it seems that calls to `glfw.get_clipboard_string` sometimes hangs.
This might be specific interactions with our software / hardware, or that in our config (FPS/ screen framerate) the clipboard was concurrently written/read by eye and world windows, causing the hangs.
In the meantime, profiling would show that a small but non-negligible portion of the CPU cycles would be spent querying the clipboard.
I here moved that call to the focus …
=> move clipboard updates to a focus callback, perfs enh + stability fix
