pupil-labs/pupil

pupil_src/shared_modules/marker_detector.py
pupil_src/shared_modules/pupil_server.py

Hey! I noticed 0.4 was not broadcasting mapped gaze position relative to tracked surfaces, so I re-enabled this feature. (I just copy-pasted + tweaked from 0.3). It seems to work fine.

broadcast mapped gaze on surfaces

---

.gitignore
pupil_src/player/main.py

For Mac and others default 1 was maintained.
For linux multiply for 10, as @mkassner have done on capture.
*.sublime-project
*.sublime-workspace

Increased vertical scroll in player (linux) and added SBT2 files to gitignore

---

pupil_src/shared_modules/plugin.py

Inheriting from list may not be a good idea, as it exposes methods that don't make sense. For instance it is possible to call append instead of add. I changed it to a list attribute and implemented __iter__ so the rest of the code is still the same.
Also, the method clean was skipping some plugins when removing the ones that were not alive. I just changed the implementation to use list comprehension.
Example of problem that may happen when removing elements inside for loop:
```
a = range(10)
for x in a:
a.remove(x)
print a # [1, 3, 5, 7, 9]
```

Refactoring Plugin_List and fixing some typos

---

pupil_src/player/main.py

typos (recording)

---

pupil_src/player/batch_exporter.py
pupil_src/player/export_launcher.py
pupil_src/player/eye_video_overlay.py
pupil_src/player/manual_gaze_correction.py
pupil_src/player/scan_path.py
pupil_src/player/vis_circle.py
pupil_src/player/vis_cross.py
pupil_src/player/vis_light_points.py
pupil_src/player/vis_polyline.py
pupil_src/player/vis_watermark.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/marker_detector.py
pupil_src/shared_modules/offline_marker_detector.py
pupil_src/shared_modules/pupil_server.py
pupil_src/shared_modules/pupil_sync.py
pupil_src/shared_modules/show_calibration.py

#231 
First commit updates vis_circle.py

Updating close button locations

---

license/update_license_header.py

Distributed under the terms of the GNU Lesser General Public License (LGPL v3.0) **License**.
Distributed under the terms of the GNU Lesser General Public License (LGPL v3.0) **license**.

happy 2016!

---

pupil_src/capture/pupil_detectors/coarse_pupil.pxd
pupil_src/capture/pupil_detectors/detector_2d.pyx
pupil_src/capture/pupil_detectors/detector_3d.pyx

Add adaptive coarse detection to 2D and 3D detector.

Coarse detection enhancement

---

pupil_src/shared_modules/calibration_routines/finish_calibration.py
pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py

Title. Small change to propagate calibration results.

Network propagate calibration notifications

---

pupil_src/capture/recorder.py
pupil_src/capture/world.py
pupil_src/player/main.py
pupil_src/shared_modules/methods.py

Improve world log

---

pupil_src/capture/eye.py
pupil_src/capture/main.py
pupil_src/shared_modules/calibration_routines/calibration_plugin_base.py
pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py
pupil_src/shared_modules/surface_tracker.py

Tested new notifications. Fixed some bugs. @mkassner Please review.

Doc and fixes

---

pupil_src/capture/world.py
pupil_src/shared_modules/zmq_tools.py

No copy __raw_data__, assert on non-list/tuple

---

pupil_src/capture/eye.py
pupil_src/capture/world.py
pupil_src/shared_modules/frame_publisher.py
pupil_src/shared_modules/zmq_tools.py

Uses `__raw_data__` feature to publish under the topic `frame.world`.

Frame Publisher plugin

---

pupil_src/shared_modules/calibration_routines/finish_calibration.py

There is no self.notify_all in finish_calibration.
So use g_pool.active_calibration_plugin.notify_all instead.

Fix notify_all

---

pupil_src/capture/recorder.py
pupil_src/player/exporter.py
pupil_src/player/main.py
pupil_src/player/player_methods.py
pupil_src/shared_modules/csv_utils.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/offline_surface_tracker.py
pupil_src/shared_modules/plugin.py
pupil_src/shared_modules/version_utils.py

Solution: Use `,` as delimiter consistently.
This includes the `info.csv` file!
TODO: Update recording version? How does this work?

Problem: CSV format not consistent

---

pupil_src/player/player_methods.py
pupil_src/player/raw_data_exporter.py
pupil_src/shared_modules/calibration_routines/gaze_mappers.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/offline_reference_surface.py
pupil_src/shared_modules/offline_surface_tracker.py

this RP renames all keys called 'base' to 'base_data' and updates old recording in this regard as well.
This PR fixes #438 .

Rename base key

---

pupil_src/shared_modules/calibration_routines/gaze_mappers.py

this PR improves the 3d intersection logic of the 3d vector gaze mapper.

Binocular 3d gaze intersection

---

pupil_src/shared_modules/calibration_routines/accuracy_test.py
pupil_src/shared_modules/calibration_routines/adjust_calibration.py

Bugfix #451

---

pupil_src/capture/eye.py
pupil_src/capture/world.py
pupil_src/shared_modules/gl_utils/utils.py

Only call UI functions if window is *visible and not iconified*. Make Plugin `gl_display()` call part of UI functions. Fixes #455

`should_call_ui_functions` implementation.

---

pupil_src/capture/world.py
pupil_src/player/exporter.py
pupil_src/player/main.py
pupil_src/player/vis_circle.py
pupil_src/shared_modules/calibration_routines/gaze_mappers.py
pupil_src/shared_modules/fixation_detector.py

Correct duration-dispersion fixation detector which uses the pupil normals' pair-wise angles as distance function for the dispersion calculation.

Pupil Angle Fixation Detector

---

pupil_src/player/vis_light_points.py

Fixes #494. Problem originated in b48f90e

Fix Vis Light Plugin

---

pupil_src/shared_modules/offline_reference_surface.py
pupil_src/shared_modules/offline_surface_tracker.py
pupil_src/shared_modules/reference_surface.py
pupil_src/shared_modules/square_marker_detect.py
pupil_src/shared_modules/surface_tracker.py

This PR:
- Improves marker tracking performace
- Improves surface learning
- Removed lens distortion model since it cause more harm then good
- Adds simple smoothing as a preview to Kalman filtering.

improve surface tracking

---

pupil_src/capture/pupil_detectors/detector_utils.pxd
pupil_src/shared_modules/calibration_routines/gaze_mappers.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/frame_publisher.py

This is helpful and auto-documents data structures.

adding topics to each data dict.

---

pupil_src/player/exporter.py
pupil_src/player/seek_bar.py
pupil_src/player/trim_marks.py

- Import runtime plugins in exporter. Fix #507 
- Make seeker more visible. Fix #351

Import runtime plugins in exporter and seekbar improvements

---

pupil_src/shared_modules/square_marker_detect.py

comment duplicated code

---

pupil_src/shared_modules/frame_publisher.py

Fix frame publisher meta data

---

pupil_src/capture/eye.py
pupil_src/capture/world.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/video_capture/base_backend.py
pupil_src/shared_modules/video_capture/fake_backend.py
pupil_src/shared_modules/video_capture/ndsi_backend.py
pupil_src/shared_modules/video_capture/uvc_backend.py

NDSI backend improvements

---

pupil_src/shared_modules/video_capture/ndsi_backend.py

Enable streaming on initial sensor refresh. Fixes problem where frame resolution and rate controls would not show.

NDSI capture improvements

---

pupil_src/capture/recorder.py
pupil_src/shared_modules/video_capture/ndsi_backend.py

Remove deprecated dict iter* methods

---

pupil_src/capture/eye.py
pupil_src/capture/main.py
pupil_src/capture/pupil_detectors/Tests/DetectorTests/test_detectors.py
pupil_src/player/exporter.py
pupil_src/player/eye_video_overlay.py
pupil_src/player/main.py
pupil_src/shared_modules/marker_detector_cacher.py
pupil_src/shared_modules/video_capture/__init__.py
pupil_src/shared_modules/video_capture/base_backend.py
pupil_src/shared_modules/video_capture/file_backend.py
pupil_src/shared_modules/video_capture/ndsi_backend.py
pupil_src/shared_modules/video_capture/uvc_backend.py

Non blocking captures

---

pupil_src/shared_modules/zmq_tools.py

`str(b'abc')` returns `"b'abc'"`
@willpatera Could you create a new bundle such that I can test LSL?

Fixing topic encoding

---

pupil_src/capture/eye.py
pupil_src/capture/world.py
pupil_src/shared_modules/zmq_tools.py

Many of these changes are spaces after `,` as described in https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements

Update to Python 3 and PEP 8 — work in progress

---

pupil_src/capture/run_capture.bat

The batch script wasn't working.
I have to do something like this.

Fix batch script for Windows

---

pupil_src/capture/run_capture.bat
pupil_src/player/exporter.py
pupil_src/player/main.py
pupil_src/player/player_methods.py
pupil_src/player/run_player.bat
pupil_src/player/vis_eye_video_overlay.py
pupil_src/player/vis_scan_path.py
pupil_src/shared_modules/file_methods.py
pupil_src/shared_modules/show_calibration.py

- resolve merge issues with `master`
- `glfw` fix
- fix recordings with `bytes` objects

Final  fixes

---

pupil_src/player/player_methods.py
pupil_src/shared_modules/annotations.py
pupil_src/shared_modules/file_methods.py
pupil_src/shared_modules/offline_surface_tracker.py

Fix annotation export bug #591 and missing catch for IsADirectoryError in player methods 🙈

Fix annotation export bug

---

pupil_src/capture/pupil_detectors/build.py
pupil_src/capture/pupil_detectors/setup.py
pupil_src/shared_modules/calibration_routines/accuracy_test.py
pupil_src/shared_modules/calibration_routines/optimization_calibration/build.py
pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py
pupil_src/shared_modules/reference_surface.py

Revert "Ongoing fixes"

---

pupil_src/player/player_methods.py
pupil_src/shared_modules/csv_utils.py
pupil_src/shared_modules/version_utils.py

- Also fixes csv header handling

Preserve Capture Software Version in info.csv

---

pupil_src/capture/recorder.py
pupil_src/player/main.py
pupil_src/player/player_methods.py
pupil_src/player/vis_eye_video_overlay.py
pupil_src/shared_modules/file_methods.py

Fix a few bugs. Improve performance. Clean up code.

Player fixes

---

pupil_src/shared_modules/fixation_detector.py

Fix fixation detector bug by setting sample_threshold depending on cpature frame rate

---

pupil_src/capture/pupil_detectors/build.py
pupil_src/capture/recorder.py
pupil_src/shared_modules/audio/__init__.py
pupil_src/shared_modules/calibration_routines/optimization_calibration/build.py

...and use selection getter for Audio recording inputs

Fix Unicode Decode Errors 

---

pupil_src/capture/eye.py
pupil_src/capture/recorder.py
pupil_src/shared_modules/av_writer.py
pupil_src/shared_modules/video_capture/base_backend.py
pupil_src/shared_modules/video_capture/ndsi_backend.py

Pupil Mobile h.264 streaming

---

pupil_src/shared_modules/audio_capture.py

remove needless enumerate call

---

pupil_src/player/player_methods.py
pupil_src/player/vis_eye_video_overlay.py

Replaces #739 
Fixes #735 and #738

Fix Eye Overlay plugin, take 2

---

.gitignore
pupil_src/player/main.py

Create plugins folder for Player if not existing

---

pupil_src/shared_modules/calibration_routines/__init__.py
pupil_src/shared_modules/calibration_routines/one_target_calibration.py
pupil_src/shared_modules/calibration_routines/single_marker_calibration.py

Added a new calibration routine: A single gaze target is displayed statically on the screen, the user gazes onto the target while moving his head to quickly sample many different gaze angles. 
With this routine one can quickly sample a great range densely.

Added one target calibration

---

pupil_src/capture/pupil_detectors/setup.py
pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py

This PR aligns with current documentation in pupil-docs/master branch for developer environment setup on Windows. 
Paths are set relative to the instructions in the docs, but can be modified based on the individual developer's setup. 
pupil detector setup.py - https://docs.pupil-labs.com/master/#modify-pupil-detectors-setup-py
optimization calibration setup.py - https://docs.pupil-labs.com/master/#modify-optimization-calibration-setup-py

Update reference paths for pupil detector and calibration builds on Windows

---

pupil_src/launchables/marker_detectors.py
pupil_src/launchables/player.py
pupil_src/main.py
pupil_src/shared_modules/annotations.py
pupil_src/shared_modules/background_helper.py
pupil_src/shared_modules/batch_exporter.py
pupil_src/shared_modules/calibration_routines/adjust_calibration.py
pupil_src/shared_modules/calibration_routines/camera_intrinsics_estimation.py
pupil_src/shared_modules/calibration_routines/natural_features_calibration.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/gaze_producers.py
pupil_src/shared_modules/marker_auto_trim_marks.py
pupil_src/shared_modules/pupil_producers.py
pupil_src/shared_modules/seek_bar.py
pupil_src/shared_modules/surface_tracker.py
pupil_src/shared_modules/trim_marks.py
pupil_src/shared_modules/video_export_launcher.py
pupil_src/shared_modules/vis_circle.py
pupil_src/shared_modules/vis_cross.py
pupil_src/shared_modules/vis_eye_video_overlay.py
pupil_src/shared_modules/vis_fixation.py
pupil_src/shared_modules/vis_light_points.py
pupil_src/shared_modules/vis_polyline.py
pupil_src/shared_modules/vis_scan_path.py
pupil_src/shared_modules/vis_watermark.py

- Make marker detection a launchable
- Fix offline pupil detection
- Change all deprecated `update()` functions to `recent_events()`

Player launcher enhancements

---

pupil_src/shared_modules/blink_detection.py
pupil_src/shared_modules/gaze_producers.py

Refactor blink detector

---

pupil_src/shared_modules/gaze_producers.py
pupil_src/shared_modules/vis_eye_video_overlay.py

Create wrapper that implements loading, frame management and drawing for each each eye separately.

Refactor Eye Video Overlay

---

pupil_src/shared_modules/blink_detection.py

Visualize blink onsets and offsets

---

pupil_src/launchables/world.py
pupil_src/shared_modules/plugin.py
pupil_src/shared_modules/video_capture/file_backend.py
pupil_src/shared_modules/video_capture/realsense_backend.py
pupil_src/shared_modules/video_capture/uvc_backend.py

`File_Manager` will activate video files if they were dropped on the main window.

Plugin.on_drop + fixes

---

pupil_src/launchables/world.py
pupil_src/shared_modules/calibration_routines/single_marker_calibration.py
pupil_src/shared_modules/csv_utils.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/player_methods.py
pupil_src/shared_modules/square_marker_detect.py
pupil_src/shared_modules/video_capture/file_backend.py
pupil_src/shared_modules/zmq_tools.py

Final fixes before v0.9.14 release

---

pupil_src/launchables/world.py
pupil_src/shared_modules/dialation_history.py

Uses `pylgui.Bar_Graph`s to visualize the `diameter_3d` value for pupil positions with confidence `>0.6`

Dilation History plugin for Pupil Capture

---

pupil_src/shared_modules/reference_surface.py

Fix rotated heatmaps

---

pupil_src/shared_modules/raw_data_exporter.py

Fix raw data exporter docs inconsistency

---

pupil_src/launchables/player.py
pupil_src/launchables/world.py
pupil_src/shared_modules/gaze_producers.py
pupil_src/shared_modules/offline_surface_tracker.py
pupil_src/shared_modules/pupil_producers.py

Fixes #852 and partially #857 
**Requires `pyglui v1.10`**
Features:
- Reintroduce manual gaze correction
- Hide gaze sections from timeline
- `Jump to next natural feature` button
- Differentiate visually if natural feature belongs to current frame (filled circle) or if it is only nearby (circle outline, more transparent the further away it is )

Offline calibration improvements

---

pupil_src/shared_modules/pupil_producers.py
pupil_src/shared_modules/seek_control.py
pupil_src/shared_modules/video_capture/file_backend.py

Allow to pause offline pupil detection

---

pupil_src/shared_modules/exporter.py
pupil_src/shared_modules/video_export_launcher.py

Plugin_List was not initialized correctly

Fix video export bug

---

pupil_src/launchables/world.py
pupil_src/shared_modules/calibration_routines/__init__.py
pupil_src/shared_modules/camera_intrinsics_estimation.py

This plugin has been part of the calibration routines previously. It does not fit this category. Therefore, we have decided to convert it to a stand-alone plugin.

Make camera intrinsics estimation a normal plugin

---

pupil_src/launchables/eye.py

This makes the graph positioning consistent across all processes.

Update eye process graph positions

---

pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
pupil_src/shared_modules/pupil_detectors/detector_3d.pyx

Change "Minimum Pupil Size" default from 30 to 20

---

pupil_src/shared_modules/calibration_routines/optimization_calibration/setup.py
pupil_src/shared_modules/pupil_detectors/setup.py

Update opencv lib and include paths to match homebrew migration

---

pupil_src/shared_modules/background_helper.py

Fix exception when double-canceling a background task.

---

pupil_src/shared_modules/fixation_detector.py

Uses [`scipy.spatial.distance.pdist`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html#scipy.spatial.distance.pdist) + `cosine` metric instead of custom `cv2.minEnclosingCircle` + spherical coordinate solution. 
There is no noticeable difference in computation time for the offline detector nor a noticeable increase in CPU usage in the online detector compared to the previous version.
- Fix binary search result when target index was on the left edge of the search space
- Unify fixation visualization: Yellow, non-filled circle
- Add fixation constraint assertions

Fixation detector improvements

---

.gitignore
pupil_src/launchables/service.py
pupil_src/shared_modules/calibration_routines/hmd_calibration.py

- Service: Fix outdated plugin list initializer argument
- HMD calibration: Consistent success/failure notifications for both 2d and 3d calibration modes.

HMD Calibration Improvements

---

pupil_src/launchables/player.py
pupil_src/shared_modules/batch_exporter.py
pupil_src/shared_modules/exporter.py

Re-enable this plugin when fixing #911 and #914

Disable Marker Auto Trim Marks and Batch Exporter plugins

---

pupil_src/shared_modules/background_helper.py
pupil_src/shared_modules/exporter.py
pupil_src/shared_modules/video_export_launcher.py

Fixes #914. Next step is to re-enable and adapt the batch exporter plugin.

Refactor video exporter to use background helper

---

pupil_src/launchables/player.py
pupil_src/launchables/world.py

Include hdpi factor when calculating click event location

---

pupil_src/shared_modules/offline_surface_tracker.py

Offline Surface Tracker: Add confidence column to gaze export

---

pupil_src/launchables/eye.py

Eye: Remove "Integrated Camera" from preferred camera list

---

pupil_src/shared_modules/exporter.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/video_export_launcher.py

Fixation Detector: Fix attribute errors on export

---

pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py
pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
pupil_src/shared_modules/calibration_routines/single_marker_calibration.py
pupil_src/shared_modules/circle_detector.py

- `CircleTracker.update()` function returns all detected markers.
- The [Ref marker and stop marker](
https://drive.google.com/drive/folders/115FF7xto9knjz62_Oa_QIBmV_39y4Dd_) have been redesigned. They can be used for Manual Marker Calibration within a distance of 2.5 meters under normal lighting condition.
- In `manual_marker_calibration`, `screen_marker_calibration` and `single_marker_calibration`, the largest circle of all detected markers are drawn. If more than one markers are detected, there will be warning.
- In `screen_marker_calibration` and `single_marker_calibration`, the Ref marker has been redesigned.

Improve the accuracy and efficiency of the marker detection

---

pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py
pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
pupil_src/shared_modules/calibration_routines/single_marker_calibration.py

If more than one markers are detected, the area of the markers will be filled with red.

Show warning if more than one markers are detected

---

pupil_src/shared_modules/camera_intrinsics_estimation.py
pupil_src/shared_modules/hololens_relay.py

Update Icon font and character for `camera intrinsics estimation` and `hololens relay` plugins

Update plugin icon chr

---

pupil_src/launchables/world.py
pupil_src/main.py
pupil_src/shared_modules/calibration_routines/gaze_mappers.py
pupil_src/shared_modules/plugin.py
pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
pupil_src/shared_modules/pupil_detectors/detector_3d.pyx

This bundle includes a series of small fixes
1. Player bundle: Fix passing recording as argument, fixes #810
2. Update detector and gaze mapper icons
3. Improve main menu collapse behavior, requires https://github.com/pupil-labs/pyglui/pull/86 to be merged

Fix player args, detector icons and improve menu collapse behavior

---

pupil_src/shared_modules/accuracy_visualizer.py

Maybe we should think about renaming the plugin to `Accuracy Calculater` or something similar.

Accuracy Visualizer: Fix and opt-out visualization

---

pupil_src/shared_modules/calibration_routines/single_marker_calibration.py

- modify marker display modes in Single Marker Calibration to be 'Full screen', 'Window', 'Manual'
- make stop marker work in Single Marker Calibration

Modify marker display modes in Single Marker Calibration

---

pupil_src/launchables/eye.py
pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
pupil_src/shared_modules/pupil_detectors/detector_3d.pyx
pupil_src/shared_modules/ui_roi.py

- Disable coarse detection for frames with width <= 200. The image is so small already that a further reduction in ROI is not beneficent anymore.
- Improve user ROI UX

Detector improvements

---

pupil_src/launchables/player.py
pupil_src/shared_modules/seek_control.py
pupil_src/shared_modules/video_capture/file_backend.py

- Playback mode: Shows pause button and seek buttons decrease/increase playback speed (Fixes #37 )
- Frame-by-frame mode: Shows play button and seek buttons seek by one frame only
- Improved transition from point & click seek to drag-handle seek mode
Requires `pyglui >= v1.14`, PR: https://github.com/pupil-labs/pyglui/pull/91

Player UI improvements

---

pupil_src/launchables/player.py
pupil_src/launchables/world.py
pupil_src/shared_modules/service_ui.py

Requires `pyglui >=v1.15`, https://github.com/pupil-labs/pyglui/pull/93

Clipboard support

---

pupil_src/launchables/eye.py

Eye: Calculate mouse pos correctly on retina displays

---

pupil_src/launchables/player.py
pupil_src/shared_modules/seek_control.py
pupil_src/shared_modules/video_capture/file_backend.py

Convert from index-based to time-based drawing:
Requires `pyglui v1.16`, https://github.com/pupil-labs/pyglui/pull/94

Timebased seeking

---

pupil_src/shared_modules/fixation_detector.py

fix inconsistency in confidence filter

---

pupil_src/shared_modules/annotations.py

Offline Annotation: Refactor csv export

---

pupil_src/launchables/player.py

TYPO: exsits -> exists

---

pupil_src/launchables/player.py
pupil_src/shared_modules/blink_detection.py
pupil_src/shared_modules/gaze_producers.py
pupil_src/shared_modules/offline_surface_tracker.py
pupil_src/shared_modules/system_timelines.py

Requires [`pylgui v1.18`](https://github.com/pupil-labs/pyglui/pull/97)
- Cache offline blink detection timeline data
- Improves timeline height consistency for
- Offline Blink Detection
- FPS Timeline
- Improves offline calibration section visualization on Retina displays

Player timeline improvements

---

pupil_src/launchables/eye.py
pupil_src/launchables/player.py
pupil_src/launchables/world.py
pupil_src/shared_modules/annotations.py
pupil_src/shared_modules/blink_detection.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/offline_surface_tracker.py
pupil_src/shared_modules/seek_control.py
pupil_src/shared_modules/service_ui.py
pupil_src/shared_modules/video_export_launcher.py

- Fixation detector: Jump to previous fixation button and wrap-around seeking
- Avoid GLFW window creation failures where passed window size dimension is zero
- Trimmed section looped playback
- Consistent export range handling in all built-in plugins
- Export folder names are named by trim section time instead of index range

v1.4 feature collection

---

pupil_src/shared_modules/fixation_detector.py

Offline Fixation Detector: Set upper bound for max_duration to 4000

---

pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
pupil_src/shared_modules/calibration_routines/single_marker_calibration.py
pupil_src/shared_modules/camera_intrinsics_estimation.py

Capture: Make selected monitor persistent for screen-based calibration plugins

---

pupil_src/launchables/eye.py
pupil_src/launchables/player.py
pupil_src/launchables/world.py
pupil_src/shared_modules/service_ui.py

- Improve default window positions on Windows. Fixes #1075

v1.5 bug fix collection

---

.gitignore
pupil_src/launchables/eye.py
pupil_src/launchables/service.py
pupil_src/shared_modules/frame_publisher.py
pupil_src/shared_modules/video_capture/uvc_backend.py
pupil_src/shared_modules/zmq_tools.py

v1.5 features and bug fixes

---

pupil_src/launchables/world.py
pupil_src/shared_modules/batch_exporter.py
pupil_src/shared_modules/blink_detection.py

fixed typos in `world.py`
fixed typos in `Batch exporter` plugin

Fix typos in Pupil repo

---

pupil_src/launchables/world.py
pupil_src/shared_modules/audio/__init__.py
pupil_src/shared_modules/audio_capture.py

1. Use pyaudio to list capture devices
2. Fix stream finalization issue
3. Set output sampling rate equal to input rate
4. Simpler output timestamps calculation

Audio capture support on Windows

---

pupil_src/shared_modules/imotions_exporter.py

This plugin exports Pupil recordings in a format that can be imported in the [iMotions](https://imotions.com/eye-tracking/) software.

Add iMotions Exporter

---

pupil_src/launchables/world.py
pupil_src/shared_modules/accuracy_visualizer.py

- Make `Accuracy Visualizer` a default plugin
- Visualize calibration area
- Add doc text to the menu

Accuracy Visualizer improvements

---

pupil_src/shared_modules/audio/__init__.py
pupil_src/shared_modules/audio_capture.py

Experimental. On mac it will print diagnostic info in the console, and will not populate the list

Use PyAudio to list devices on Linux and Darwin

---

pupil_src/main.py
pupil_src/shared_modules/log_display.py

In-app logs: Only INFO level and higher
Console logs: INFO level and higher by default, includes DEBUG if specified
Log file logs: Always all levels

Make logging consistent

---

pupil_src/shared_modules/video_capture/utils.py

Make the condition of reporting stripes more strict and robust

Update the stripes checking logic for 200HZ camera

---

pupil_src/launchables/player.py
pupil_src/shared_modules/audio_capture.py
pupil_src/shared_modules/audio_playback.py
pupil_src/shared_modules/audio_utils.py
pupil_src/shared_modules/av_writer.py
pupil_src/shared_modules/system_timelines.py
pupil_src/shared_modules/video_capture/file_backend.py
pupil_src/shared_modules/vis_eye_video_overlay.py

**Requires** [Update to 0.4 baseline, extend filter functionality](https://github.com/pupil-labs/PyAV/pull/8)
**Requires** [Changes for rendering of audio vizualization](https://github.com/pupil-labs/pyglui/pull/101)
1. Changes to reflect PyAv 0.4.0 API update
2. Experimental implementation of volume control through libavfilter
3. Audio vizualization in System_Timelines

EXPERIMENTAL: Volume control through libavfilter, audio vizualization

---

pupil_src/shared_modules/background_helper.py
pupil_src/shared_modules/calibration_routines/calibrate.py
pupil_src/shared_modules/camera_models.py

Refactor calibration data preprocessing

---

deployment/bundle.sh
deployment/deploy_capture/finalize_bundle.py
deployment/deploy_player/finalize_bundle.py
deployment/deploy_service/finalize_bundle.py
pupil_src/shared_modules/version_utils.py

Instead of simply using the most recent tag that could also be maj.min.patch.

bundle.sh: Format version based on most recent maj.min tag

---

pupil_src/shared_modules/av_writer.py

Fix mjpeg invalid frame rate issue

---

pupil_src/shared_modules/accuracy_visualizer.py
pupil_src/shared_modules/blink_detection.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/gaze_producers.py
pupil_src/shared_modules/offline_surface_tracker.py
pupil_src/shared_modules/pupil_producers.py
pupil_src/shared_modules/raw_data_exporter.py

- Improve accuracy visualizer persistency
- Fix blink filter symmetry
- Usage of `itertools.chain.from_iterable`
- Fix offline pupil detection cache version validation

Bug fixes and setting persistency improvements

---

pupil_src/shared_modules/video_capture/uvc_backend.py

The switch would only appear in Pupil Cam2 menu

Add switch for Check Stripes in the menu

---

pupil_src/shared_modules/recorder.py

Warning threshold: 5GB
Recording stop threshold: 1GB
Fixes #1201

Warn user on low disk space and stop recording if critically low

---

pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py

Manual Marker Calib: Reset last ref location on stop

---

pupil_src/shared_modules/video_capture/uvc_backend.py

1. Remove "load defaults" button
2. Add exception for 'Absolute Exposure Time' KeyError

[uvc_backend] Remove "load defaults" button of camera setting

---

pupil_src/shared_modules/player_methods.py

Fixes #1221 by mirroring behavior on Unix (replacing old file with new file).
Also refactors `video_*` variable names to `media_*` since it is used for audio files as well.

Fix os.rename exception on Windows during PM recording upgrade

---

pupil_src/shared_modules/raw_data_exporter.py

I didn't know how to claim the task ;)
Integrated Switches.

Set parameter for Raw Data Exporter in Pupil Player #1239

---

pupil_src/launchables/player.py
pupil_src/shared_modules/eye_video_exporter.py
pupil_src/shared_modules/imotions_exporter.py
pupil_src/shared_modules/player_methods.py
pupil_src/shared_modules/pupil_producers.py
pupil_src/shared_modules/video_exporter.py
pupil_src/shared_modules/vis_eye_video_overlay.py

Adds an Eye Video Export plugin that also supports rendering the detected pupil on the video.
Common functionality of this plugin and the iMotions plugin was extracted into a VideoExporter
fixes #1294

Eye Video Exporter

---

pupil_src/shared_modules/imotions_exporter.py
pupil_src/shared_modules/video_exporter.py

iMotions exporter: Add support for world-less recordings

---

pupil_src/shared_modules/background_helper.py
pupil_src/shared_modules/batch_exporter.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/gaze_producers.py
pupil_src/shared_modules/imotions_exporter.py
pupil_src/shared_modules/video_export_launcher.py
pupil_src/shared_modules/video_exporter.py
pupil_src/shared_modules/zmq_tools.py

Fixed background logging issue by replacing zmq handler with a StreamHandler

---

pupil_src/launchables/player.py
pupil_src/launchables/world.py
pupil_src/shared_modules/audio_capture.py
pupil_src/shared_modules/blink_detection.py

Applies to some files that were not covered in https://github.com/pupil-labs/pupil/pull/1344

Apply Black to missed files

---

pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
pupil_src/shared_modules/pupil_detectors/detector_3d.pyx

Decrease Maximum Pupil Size

---

pupil_src/launchables/world.py

Requires `value` field, unit: confidence

World: Add set_min_calibration_confidence notification

---

pupil_src/launchables/world.py
pupil_src/shared_modules/annotations.py
pupil_src/shared_modules/player_methods.py

Fix Annotations

---

pupil_src/shared_modules/video_capture/realsense2_backend.py

This can List and select frame sizes and rates
_Align Stream_ and _Stream Preset_ features are temporarily removed.

Rs2 frame rate and size setter

---

pupil_src/shared_modules/video_capture/realsense2_backend.py

Can record (pseudo-colored) depth video.
Tested with various resolution and frame rates.

Realsense2 record rgb and depth frames

---

pupil_src/shared_modules/video_capture/fake_backend.py

Fake Backend: Fix playback afte seeking

---

pupil_src/shared_modules/fixation_detector.py

Fixation Detector: Fix export format

---

pupil_src/shared_modules/video_capture/realsense2_backend.py

Tested against many cases, but still fails on Test 03. See test procedures below.
Test procedures are also in progress. (i.e. expect more tests)
**Test 01**
_Initial condition_: NO `user_settings_*` present
1. Start plugged
- Eye cameras online after a while
2. Select Realsense D400 manager
3. Activate source Intel RealSense D415
- All feeds online.
5. Change resolution/fps (can Reset to default settings as well)
6. Record video (rgb + depth + eye)
=> SUCCESS
**Test 02**
_Initial condition_: NO `user_settings_*` present
1. Start unplugged
2. Select Realsense D400 manager
3. Plug device
- Eye cameras online after a while
4. Activate source Intel RealSense D415
- All feeds online.
5. Change resolution/fps (can Reset to default settings as well)
6. Record video (rgb + depth + eye)
=> SUCCESS …

Rs2 stability improvements

---

pupil_src/shared_modules/observable.py
pupil_src/shared_modules/observable_test.py

BTW: this is going to a feature branch, not master

New Observable Class

---

pupil_src/shared_modules/tasklib/__init__.py
pupil_src/shared_modules/tasklib/background/__init__.py
pupil_src/shared_modules/tasklib/background/create.py
pupil_src/shared_modules/tasklib/background/patches.py
pupil_src/shared_modules/tasklib/background/shared_memory.py
pupil_src/shared_modules/tasklib/background/task.py
pupil_src/shared_modules/tasklib/interface.py
pupil_src/shared_modules/tasklib/manager.py
pupil_src/shared_modules/tasklib/observers.py

depends on https://github.com/pupil-labs/pupil/pull/1389

New Background Tasks Module

---

pupil_src/shared_modules/av_writer.py
pupil_src/shared_modules/video_export/plugin_base/isolated_frame_exporter.py
pupil_src/shared_modules/video_export/plugins/eye_video_exporter.py
pupil_src/shared_modules/video_export/plugins/imotions_exporter.py
pupil_src/shared_modules/video_export/plugins/world_video_exporter.py

Export video timestamps as npy and csv

---

pupil_src/shared_modules/pupil_remote.py

Fixes #1435 
@fx-lange please review

Log Pupil Remote protocol requests and responses

---

pupil_src/launchables/marker_detectors.py
pupil_src/launchables/player.py
pupil_src/shared_modules/marker_detector_cacher.py
pupil_src/shared_modules/update_methods.py
pupil_src/shared_modules/video_capture/__init__.py
pupil_src/shared_modules/video_capture/file_backend.py
pupil_src/shared_modules/video_capture/utils.py
pupil_src/shared_modules/video_export/plugins/world_video_exporter.py

In our previous implement, we didn't handle lookup.container_idx for broken videos correctly, if the video is broken, we should not update its container_idx.

Fixed broken videos error and cleanup code

---

pupil_src/shared_modules/update_methods.py

add explicit error messages for `check_for_worldless_recording` function

Add explicit error messages

---

pupil_src/launchables/eye.py
pupil_src/shared_modules/video_capture/base_backend.py
pupil_src/shared_modules/video_capture/fake_backend.py
pupil_src/shared_modules/video_capture/file_backend.py
pupil_src/shared_modules/video_capture/ndsi_backend.py
pupil_src/shared_modules/video_capture/uvc_backend.py

Implements feature, as requested in #1278

1278 camera auto selection

---

pupil_src/launchables/eye.py
pupil_src/shared_modules/update_methods.py
pupil_src/shared_modules/video_capture/base_backend.py
pupil_src/shared_modules/video_capture/utils.py
pupil_src/shared_modules/video_capture/uvc_backend.py

This PR adds full compatibility for the new eye cameras shipped with the new 200Hz HTC Vive Binocular Add-on.

Pupil Cam3 support

---

pupil_src/launchables/eye.py
pupil_src/launchables/marker_detectors.py
pupil_src/launchables/player.py
pupil_src/launchables/service.py
pupil_src/launchables/world.py
pupil_src/shared_modules/file_methods.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
pupil_src/shared_modules/gaze_producer/worker/create_calibration.py
pupil_src/shared_modules/gaze_producer/worker/map_gaze.py
pupil_src/shared_modules/head_pose_tracker/worker/detection_worker.py
pupil_src/shared_modules/marker_detector_cacher.py
pupil_src/shared_modules/pupil_producers.py
pupil_src/shared_modules/video_capture/tests/file_backend/test_file_backend.py
pupil_src/shared_modules/video_export/plugin_base/isolated_frame_exporter.py
pupil_src/shared_modules/video_overlay/workers/frame_fetcher.py
pupil_src/shared_modules/vis_eye_video_overlay.py

- Replace custom `file_methods.FrozenDict` with `types.MappingProxyType`
- Replace empty class definitions with `types.SimpleNamespace`

Use builtin types

---

pupil_src/shared_modules/video_capture/utils.py

Ignore time files and stop at first working video file

Fix Pupil Mobile intrinsics lookup

---

pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py
pupil_src/shared_modules/eye_movement/eye_movement_detector_real_time.py
pupil_src/shared_modules/eye_movement/model/__init__.py
pupil_src/shared_modules/eye_movement/model/color.py
pupil_src/shared_modules/eye_movement/model/segment.py
pupil_src/shared_modules/eye_movement/ui/__init__.py
pupil_src/shared_modules/eye_movement/ui/segment_overlay.py
pupil_src/shared_modules/player_methods.py

Eye movement visualization

---

pupil_src/shared_modules/eye_movement/controller/__init__.py
pupil_src/shared_modules/eye_movement/controller/eye_movement_csv_exporter.py
pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py
pupil_src/shared_modules/eye_movement/eye_movement_detector_real_time.py
pupil_src/shared_modules/eye_movement/model/__init__.py
pupil_src/shared_modules/eye_movement/model/color.py
pupil_src/shared_modules/eye_movement/model/segment.py
pupil_src/shared_modules/eye_movement/utils.py
pupil_src/shared_modules/eye_movement/worker/real_time_buffered_detector.py

Instead of having to map segments to surfaces, we can just rely on mapping gaze data to surfaces and then correlating them to the `eye_movement_by_gaze.csv` output.

 Export eye movements by gaze and by segment 

---

pupil_src/shared_modules/surface_tracker/background_tasks.py
pupil_src/shared_modules/surface_tracker/cache.py
pupil_src/shared_modules/surface_tracker/gui.py
pupil_src/shared_modules/surface_tracker/surface.py
pupil_src/shared_modules/surface_tracker/surface_offline.py
pupil_src/shared_modules/surface_tracker/surface_tracker.py
pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py

Removes explicit fixation mapping in favor of #1516

Surface tracker improvements

---

pupil_src/shared_modules/player_methods.py

Allow passing Python lists as target to player_methods.find_clostest()

---

pupil_src/shared_modules/video_capture/ndsi_backend.py

This is related to work done for #1518

Add PI support for ndsi auto-selection

---

pupil_src/launchables/world.py

This is related to work done for #1518

Add adapt_window_size notification handle in world process

---

pupil_src/launchables/player.py
pupil_src/launchables/world.py
pupil_src/shared_modules/calibration_routines/manual_marker_calibration.py
pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/saccade_detector.py
pupil_src/shared_modules/video_export/plugins/world_video_exporter.py
pupil_src/shared_modules/vis_fixation.py

Reverts pupil-labs/pupil#1519 in favor of a transition period between fixation detector and eye movement detector.

Revert "Remove deprecated detector plugins"

---

pupil_src/shared_modules/eye_movement/utils.py
pupil_src/shared_modules/fixation_detector.py

This is related to #1536. This is a quick and temporary fix, but not definitive and comprehensive.

Quick fix for eye movement 3d consistency check

---

pupil_src/shared_modules/surface_tracker/surface.py

Fix issue #1544

---

pupil_src/shared_modules/video_capture/uvc_backend.py

Problem: Stripe Detector was initialised for Pupil Cam2 and Cam3. On frame size changes, the stripe detector was only re-initialised for Pupil Cam2 (line 444), leading to crashes when using Pupil Cam3.
Solution: Disable Stripe Detector for Pupil Cam3 since these cameras do not show the stripe issue. Introduces new read-only property that is used to consistently decide whether to initialize the tripe detector or not. Also improves some variable names.

Disable Stripe Detector for Pupil Cam3

---

pupil_src/shared_modules/stdlib_utils.py

Separate PR for @romanroibu's unique iterable type. I would like to use it in #1562

Add unique iterable type

---

pupil_src/shared_modules/head_pose_tracker/function/bundle_adjustment.py
pupil_src/shared_modules/head_pose_tracker/worker/detection_worker.py
pupil_src/shared_modules/head_pose_tracker/worker/optimization_worker.py

1. Improve the effectiveness of optimization of 3d markers model
1. Filter duplicate detected markers

Improve head pose tracker

---

pupil_src/shared_modules/head_pose_tracker/function/bundle_adjustment.py
pupil_src/shared_modules/head_pose_tracker/function/solvepnp.py
pupil_src/shared_modules/head_pose_tracker/function/triangulate_marker.py
pupil_src/shared_modules/head_pose_tracker/worker/optimization_worker.py

remove pose translation vector boundary limit
add handling to error from _least_squares

Head Pose Tracker: Remove translation value constraints

---

pupil_src/launchables/eye.py

ROI API: Fix naming and argument order

---

pupil_src/launchables/eye.py
pupil_src/launchables/player.py
pupil_src/launchables/world.py

Make input event consumption explicit

---

pupil_src/shared_modules/eye_movement/ui/menu_content.py
pupil_src/shared_modules/eye_movement/utils.py
pupil_src/shared_modules/eye_movement/worker/offline_detection_task.py
pupil_src/shared_modules/eye_movement/worker/real_time_buffered_detector.py

Fix eye movement 3d consistency check

---

pupil_src/shared_modules/video_capture/hmd_streaming.py

fix for checking if projection matrix is defined

---

pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py

Surface tracker fix background processing 2

---

pupil_src/shared_modules/remote_recorder.py
pupil_src/shared_modules/video_capture/ndsi_backend.py

This depends on [`pyndsi` PR #44](https://github.com/pupil-labs/pyndsi/pull/44).

Integrate multi-version ndsi

---

pupil_src/shared_modules/video_capture/uvc_backend.py

Disable windows hardware timestamps

---

pupil_src/launchables/player.py

This allows Player to display more feedback in case the user attempted to open an invalid recording.

Player drop: Implement multi-line tip

---

pupil_src/shared_modules/eye_movement/eye_movement_detector_offline.py

Save eye movements to disk when detection is completed

---

pupil_src/main.py
pupil_src/shared_modules/launchable_args.py

Add version cli argument

---

pupil_src/shared_modules/surface_tracker/surface.py

When editing surface corners, often the corners would not match with the mouse position.
Here's the fix. Most important is the 2nd commit.

Fix surface corner drag inaccuracies

---

pupil_src/shared_modules/video_capture/ndsi_backend.py

Enables detection of NDSI v4 devices, e.g. PI Companion app.
TODO:

Support streaming Pupil Invisible camera

---

deployment/deploy_capture/finalize_bundle.py
deployment/deploy_player/finalize_bundle.py
deployment/deploy_service/finalize_bundle.py
pupil_src/launchables/player.py
pupil_src/launchables/service.py
pupil_src/launchables/world.py
pupil_src/shared_modules/batch_exporter.py
pupil_src/shared_modules/calibration_routines/screen_marker_calibration.py
pupil_src/shared_modules/calibration_routines/single_marker_calibration.py
pupil_src/shared_modules/camera_intrinsics_estimation.py
pupil_src/shared_modules/camera_models.py
pupil_src/shared_modules/head_pose_tracker/storage/general_settings.py
pupil_src/shared_modules/head_pose_tracker/storage/optimization_storage.py
pupil_src/shared_modules/methods.py
pupil_src/shared_modules/player_methods.py
pupil_src/shared_modules/pupil_remote.py
pupil_src/shared_modules/recorder.py
pupil_src/shared_modules/square_marker_detect.py
pupil_src/shared_modules/video_capture/ndsi_backend.py
pupil_src/shared_modules/video_capture/uvc_backend.py
pupil_src/shared_modules/vis_light_points.py

Do not catch system exceptions

---

pupil_src/launchables/eye.py
pupil_src/launchables/player.py
pupil_src/launchables/service.py
pupil_src/launchables/world.py
pupil_src/shared_modules/background_helper.py
pupil_src/shared_modules/gaze_producer/worker/create_calibration.py
pupil_src/shared_modules/gaze_producer/worker/map_gaze.py
pupil_src/shared_modules/os_utils.py
pupil_src/shared_modules/tasklib/background/patches.py
pupil_src/shared_modules/tasklib/manager.py

Handle keyboard interrupts gracefully

---

README.md
docs/dependencies-realsense-r200.md

Added install instructions for Intel RealSense R200/D400

Realsense docs

---

pupil_src/shared_modules/pupil_detectors/detector_2d.pyx

This pull request fixes bug #1691. It is probably one of the simplest bugfixes in history while the bug itself is sometimes quite annoying...

Fix bug #1691

---

pupil_src/shared_modules/fixation_detector.py

Please see commit messages for reference:
- https://github.com/pupil-labs/pupil/commit/515783161abdf0165ab1898ae2ac83b992916251
- https://github.com/pupil-labs/pupil/commit/f9720e10a512625e4b1e161f0f498b79b90257ec
- https://github.com/pupil-labs/pupil/commit/e84101b20f20b97e4a35d3d5c4e639b08a3ccf42

Fixation detector fixes

---

docs/dependencies-macos.md
docs/dependencies-ubuntu17.md
docs/dependencies-ubuntu18.md
docs/dependencies-windows.md

Update developer docs on new situation with pupil-detectors package.
This should go into master like a hotfix (for visibility) and then we can pull into develop.

Pupil detectors docs

---

pupil_src/shared_modules/head_pose_tracker/controller/online_controller.py

A small patch to stream the head pose of the plug-in head pose tracker to the ZMQ topic `head_pose`.

Stream Head Pose to ZMQ

---

pupil_src/shared_modules/video_capture/uvc_backend.py

Sets invalid frame timestamp log level to debug

---

pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
pupil_src/shared_modules/scan_path/controller.py
pupil_src/shared_modules/storage.py

V1.23 fixes

---

pupil_src/shared_modules/scan_path/controller.py

Logging each step is just too much. :)

Scanpath/Gaze history: Remove update logs

---

pupil_src/shared_modules/scan_path/controller.py

Fix Pupil Player crash when exporting while gaze history is computed

---

pupil_src/shared_modules/background_helper.py
pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py

Avoid crashing Surface Tracker if exports are active

---

pupil_src/shared_modules/video_export/plugins/eye_video_exporter.py
pupil_src/shared_modules/video_overlay/plugins/eye_overlay.py
pupil_src/shared_modules/video_overlay/utils/image_manipulation.py

Renders
- 2d pupil ellipse in blue
- 3d reprojected pupil ellipse in red
- 3d eye model outline in green

Visualize available 2d and 3d pupil ellipses in eye overlay and eye video exporter

---

pupil_src/launchables/eye.py
pupil_src/launchables/service.py
pupil_src/launchables/world.py
pupil_src/shared_modules/calibration_choreography/screen_marker_plugin.py
pupil_src/shared_modules/hololens_relay.py
pupil_src/shared_modules/pupil_detector_plugins/detector_base_plugin.py
pupil_src/shared_modules/pupil_producers.py
pupil_src/shared_modules/service_ui.py

- `g_pool.detection_mapping_mode: str`
- replaced with `g_pool.pupil_detection_enabled: bool`
- `{"subject": "set_detection_mapping_mode", "mode": str}`
- replaced with `{"subject": "set_pupil_detection_enabled", "value": bool}`

Remove detection mapping mode

---

pupil_src/launchables/service.py
pupil_src/launchables/world.py

Please give this PR a test, once with a connected headset and once without.

Default detectors

---

pupil_src/shared_modules/system_graphs.py

- Removed the pupil diameter graphs
- Removed system graphs from menu
- Use pupil data with `pupil.0.2d` and `pupil.1.2d` detector topics for confidence graphs

Remove system graph menu

---

pupil_src/shared_modules/calibration_choreography/base_plugin.py
pupil_src/shared_modules/calibration_choreography/hmd_plugin.py
pupil_src/shared_modules/calibration_choreography/natural_feature_plugin.py
pupil_src/shared_modules/calibration_choreography/screen_marker_plugin.py
pupil_src/shared_modules/calibration_choreography/single_marker_plugin.py
pupil_src/shared_modules/gaze_mapping/gazer_2d.py
pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_headset.py
pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_hmd.py
pupil_src/shared_modules/gaze_mapping/gazer_base.py
pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py
pupil_src/shared_modules/gaze_producer/gaze_from_recording.py
pupil_src/shared_modules/gaze_producer/gaze_producer_base.py
pupil_src/shared_modules/gaze_producer/model/calibration_storage.py
pupil_src/shared_modules/gaze_producer/model/legacy/__init__.py
pupil_src/shared_modules/gaze_producer/model/legacy/calibration_storage_updater.py
pupil_src/shared_modules/gaze_producer/worker/fake_gpool.py
pupil_src/shared_modules/network_api/network_api_plugin.py
pupil_src/shared_modules/pupil_producers.py

- Removed `"Choreography"` from calibration plugins' labels
- Added custom labels for calibration plugins in selection dropdown
- Added custom order for calibration plugins in selection dropdown
- Renamed the selection dropdown label from `"Gazer"` to `"Method"`
- Added custom order for single marker modes in selection dropdown
- Added automatic hiding of marker scale for single marker calibration in `"Physical Marker"` mode

Small improvements for Pupil Core v2 (2)

---

pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_hmd.py

Was previously using the (inherited) description text from the 3D Gazer.

Update HMD Gazer description

---

pupil_src/shared_modules/accuracy_visualizer.py
pupil_src/shared_modules/calibration_choreography/base_plugin.py
pupil_src/shared_modules/calibration_choreography/hmd_plugin.py
pupil_src/shared_modules/calibration_choreography/natural_feature_plugin.py
pupil_src/shared_modules/calibration_choreography/screen_marker_plugin.py
pupil_src/shared_modules/calibration_choreography/single_marker_plugin.py

- Calibration validation button is only enabled is the selected gazer class is the same as the active gazer class

Fix calibration validation for Pupil Capture v2

---

pupil_src/shared_modules/gaze_producer/ui/calibration_menu.py

This PR fixes that recorded or imported calibrations can be deleted.

Prevent deleting imported or recorded calibratins

---

pupil_src/shared_modules/gaze_producer/model/calibration_storage.py

This PR will result in extracted recorded calibrations being overwritten when re-extracting them.
This will fix two problems:
1. Pupil v2.0 would erroneously categorize recorded calibration as offline calibrations when extracting them. Overwriting them on re-extraction will make sure we have fixed this error.
2. Since recorded calibrations will always be re-extracted upon creating a `CalibrationStorage`, we would get a warning, that we tried to add a calibration which was already existing. Now we won't get this warning anymore.

Overwrite recorded calibration when extracting

---

pupil_src/shared_modules/gaze_producer/worker/create_calibration.py

Fixes https://github.com/pupil-labs/pupil/issues/1918 partially

Correctly pass minimum calibration confidence to background process

---

pupil_src/shared_modules/calibration_choreography/base_plugin.py

Fix calibration validation for Pupil Capture v2 (2)

---

pupil_src/shared_modules/gaze_producer/controller/gaze_mapper_controller.py
pupil_src/shared_modules/gaze_producer/gaze_from_offline_calibration.py
pupil_src/shared_modules/gaze_producer/worker/create_calibration.py
pupil_src/shared_modules/gaze_producer/worker/detect_circle_markers.py
pupil_src/shared_modules/gaze_producer/worker/map_gaze.py
pupil_src/shared_modules/gaze_producer/worker/validate_gaze.py

Adopted f-string formatting over `.format()`-formatting and formatted long strings to conform with black formatting.

Gaze Producers: f-String formatting

---

pupil_src/shared_modules/gaze_producer/model/calibration_storage.py

Calculating the number of a `Recorded Calibration #`  would also take into account the identical calibration if it was extracted before. This would result in **Recorded Calibration 2** being renamed to **Recorded Calibration 3** upon opening the recording again. This bug was revealed by #1938.
After a naive approach of even more filtering for generating the new number (#1943) I decided to rewrite the suffix generation logic. The key is that we only create the recorded calibrations from the loop where we extract them from the recorded notifications. Since these are sequential, we know exactly which number every recorded calibration has and can just pass this. Since they will be overwritten anyway, this is the easiest and cleanest solution imo.

Use sequential numbering for recorded calibrations

---

pupil_src/launchables/service.py
pupil_src/shared_modules/csv_utils.py
pupil_src/shared_modules/file_methods.py
pupil_src/shared_modules/gprof2dot.py
pupil_src/shared_modules/head_pose_tracker/ui/offline_head_pose_tracker_timeline.py
pupil_src/shared_modules/hololens_relay.py
pupil_src/shared_modules/pupil_recording/update/__init__.py
pupil_src/shared_modules/recorder.py
pupil_src/shared_modules/remote_recorder.py
pupil_src/shared_modules/stdlib_utils.py
pupil_src/shared_modules/surface_tracker/background_tasks.py
pupil_src/shared_modules/surface_tracker/surface_marker.py
pupil_src/shared_modules/system_graphs.py

Fixes issues detected by the introduction of the travis black-format-check job in #1956

Apply black format to unformatted files

---

pupil_src/shared_modules/gaze_mapping/gazer_base.py

Fixes https://github.com/pupil-labs/pupil/pull/1960#pullrequestreview-443787957

Capture: Only set active gaze mapping plugin if calibration did not fail

---

pupil_src/shared_modules/gaze_producer/worker/map_gaze.py

`gazer.map_pupil_to_gaze` does not yield gaze with monotonic timestamps. Binocular pupil matches are delayed internally. To avoid non-monotonic progress updates, we use the largest timestamp that has been returned up to the current point in time.

Post-hoc gaze mapping: Avoid non-monotonic progress updates

---

pupil_src/shared_modules/annotations.py
pupil_src/shared_modules/batch_exporter.py
pupil_src/shared_modules/blink_detection.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/gaze_producer/gaze_producer_base.py
pupil_src/shared_modules/plugin.py
pupil_src/shared_modules/plugin_manager.py
pupil_src/shared_modules/pupil_producers.py
pupil_src/shared_modules/raw_data_exporter.py
pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py
pupil_src/shared_modules/video_export/plugin_base/video_exporter.py
pupil_src/shared_modules/vis_circle.py
pupil_src/shared_modules/vis_cross.py
pupil_src/shared_modules/vis_fixation.py
pupil_src/shared_modules/vis_light_points.py
pupil_src/shared_modules/vis_polyline.py
pupil_src/shared_modules/vis_watermark.py

Flatten plugin class hierarchy

---

pupil_src/shared_modules/recorder.py

This PR adds a suggestion on fixing Pupil Mobile network lag.

Better Pupil Mobile network lag error message

---

pupil_src/shared_modules/video_capture/utils.py

This PR updates the gaze timestamps file matching from a glob pattern to a regex.

Use regex to match gaze timestamp files

---

pupil_src/launchables/eye.py

Fixes https://github.com/pupil-labs/pupil/issues/2035

Support stopping eye plugins via notifications

---

pupil_src/launchables/eye.py
pupil_src/shared_modules/video_capture/hmd_streaming.py

HMD Streaming Source: Eye process and BGR/gray Frame support

---

pupil_src/shared_modules/calibration_choreography/controller/gui_window.py
pupil_src/shared_modules/calibration_choreography/controller/marker_window_controller.py

[ClickUp Task](https://app.clickup.com/t/awtbvz)

Fix GUIWindow generator yield issue

---

pupil_src/launchables/world.py
pupil_src/main.py

Fixes missing `in topic` from #2070 
Author: @bpinsard

Fix stopping launcher via Network API

---

pupil_src/shared_modules/audio_utils.py
pupil_src/shared_modules/pupil_recording/update/invisible.py

---
[ClickUp Task](https://app.clickup.com/t/b70a45)

Gracefully handle PI recordings with broken video

---

pupil_src/launchables/eye.py
pupil_src/launchables/player.py
pupil_src/launchables/world.py
pupil_src/shared_modules/gl_utils/utils.py
pupil_src/shared_modules/head_pose_tracker/ui/gl_window.py
pupil_src/shared_modules/service_ui.py
pupil_src/shared_modules/visualizer.py

This PR adds to the fixes made in https://github.com/pupil-labs/pupil/pull/2086

Selective glfw error reporting #2

---

pupil_src/shared_modules/audio_playback.py
pupil_src/shared_modules/audio_utils.py
pupil_src/shared_modules/av_writer.py
pupil_src/shared_modules/methods.py
pupil_src/shared_modules/video_capture/file_backend.py

Reverts pupil-labs/pupil#2101 - Merged into the wrong branch by accident.

Revert "Support recordings with decoding issues"

---

pupil_src/shared_modules/audio_playback.py
pupil_src/shared_modules/audio_utils.py
pupil_src/shared_modules/av_writer.py
pupil_src/shared_modules/methods.py
pupil_src/shared_modules/video_capture/file_backend.py

Mirror of #2101 but with correct merge target.

Support audio decoding issues

---

pupil_src/shared_modules/audio_playback.py
pupil_src/shared_modules/audio_utils.py

TODO:
----
[ClickUp Task](https://app.clickup.com/t/ch1ued)

Fixes laggy playback of PI recordings after seeking.

---

pupil_src/shared_modules/accuracy_visualizer.py
pupil_src/shared_modules/gaze_producer/worker/validate_gaze.py

@romanroibu Please test with a screen marker calibration:
1. Calibrate and check if visualization looks correct (Linux, Mac)
2. Consistency with previous version (one OS is sufficient)
a. Make recording in latest release
b. Open and setup post-hoc calibration and validation in latest Player release
c. Check if validation result is the same as when running this branch
I tested (1) with screenmarker and hmd calibration on Windows already.

Implement accuracy visualisation and calculation for HMD calibrations

---

pupil_src/shared_modules/audio_playback.py
pupil_src/shared_modules/audio_utils.py
pupil_src/shared_modules/av_writer.py
pupil_src/shared_modules/methods.py
pupil_src/shared_modules/video_capture/file_backend.py

This PR re-applies changes from #2107 which were not correctly applied.

Support audio decoding issues (re-applied)

---

pupil_src/shared_modules/calibration_choreography/base_plugin.py

Only run trigger_main_window_redraw() in Capture

---

pupil_src/shared_modules/accuracy_visualizer.py

Handle calibration area calculation errors

---

pupil_src/launchables/player.py
pupil_src/shared_modules/annotations.py
pupil_src/shared_modules/calibration_choreography/base_plugin.py
pupil_src/shared_modules/camera_intrinsics_estimation.py
pupil_src/shared_modules/fixation_detector.py
pupil_src/shared_modules/hotkey.py
pupil_src/shared_modules/recorder.py
pupil_src/shared_modules/surface_tracker/surface_tracker.py

This PR defines all available hotkeys in Pupil Core in a single namespace, and adds a script to generate a markdown table overview of all the hotkeys. The overview can be generated by running the `hotkey.py` file:
```
python hotkey.py
| Keyboard Shortcut   | Description                                                  |
|:--------------------|:-------------------------------------------------------------|
| `r`                 | Start and stop recording                                     |
| `c`                 | Start and stop calibration                                   |
| `t`                 | Start and stop validation                                    |
| `a`                 | Surface tracker: Add new surface                             |
| `x`                 | Add annotation …
```

Hotkey definitions

---

pupil_src/shared_modules/accuracy_visualizer.py

---
[ClickUp Task](https://app.clickup.com/t/h71f2u)

Fix validation crash if no reference data was collected

---

pupil_src/launchables/world.py
pupil_src/shared_modules/calibration_choreography/controller/marker_window_controller.py
pupil_src/shared_modules/display_recent_gaze.py
pupil_src/shared_modules/gl_utils/__init__.py
pupil_src/shared_modules/gl_utils/draw.py
pupil_src/shared_modules/gl_utils/utils.py

This PR fixes an issue where the gaze visualisation looks smaller on M1 macs, by replacing the point shader drawing with a method based on filled polygon.
---
[ClickUp Task](https://app.clickup.com/t/fh171e)

Fix gaze visualization apple silicone

---

pupil_src/shared_modules/network_time_sync.py

---
[ClickUp Task](https://app.clickup.com/t/gh0q1x)

Upgrade network time sync

---

pupil_src/shared_modules/surface_tracker/background_tasks.py
pupil_src/shared_modules/surface_tracker/surface.py

---
[ClickUp Task](https://app.clickup.com/t/h746py)

Improve surface detection consistency

---

pupil_src/shared_modules/pupil_detector_plugins/pye3d_plugin.py
requirements.txt

pye3d v0.0.7 includes the following improvements
- Simplification of `Conic` parameter calculation - [#26](https://github.com/pupil-labs/pye3d-detector/pull/26)
- Incremental performance improvements - [#27](https://github.com/pupil-labs/pye3d-detector/pull/27)
- Correctly apply corneal-refraction correction to `diameter_3d` result - [#28](https://github.com/pupil-labs/pye3d-detector/pull/28)

Bump pye3d requirement to v0.0.7

---

pupil_src/shared_modules/annotations.py

---
[ClickUp Task](https://app.clickup.com/t/kvbzbv)

Show world index in annotation log

---

pupil_src/launchables/eye.py
pupil_src/shared_modules/calibration_choreography/natural_feature_plugin.py
pupil_src/shared_modules/calibration_choreography/screen_marker_plugin.py
pupil_src/shared_modules/calibration_choreography/single_marker_plugin.py
pupil_src/shared_modules/camera_intrinsics_estimation.py
pupil_src/shared_modules/display_recent_gaze.py
pupil_src/shared_modules/marker_auto_trim_marks.py
pupil_src/shared_modules/pupil_detector_plugins/visualizer_2d.py
pupil_src/shared_modules/surface_tracker/gui.py

---
- [ClickUp Task 1](https://app.clickup.com/t/kv7gwy)
- [ClickUp Task 2](https://app.clickup.com/t/kv7jcb)

Fix M1 mac drawing calls

---

pupil_src/shared_modules/surface_tracker/offline_utils.py
pupil_src/shared_modules/surface_tracker/surface.py
pupil_src/shared_modules/surface_tracker/surface_offline.py
pupil_src/shared_modules/surface_tracker/surface_tracker_offline.py

---
[ClickUp Task](https://app.clickup.com/t/kv7jua)

Surface tracker log flood pinv fail

---

pupil_src/shared_modules/surface_tracker/background_tasks.py

---
[ClickUp Task](https://app.clickup.com/t/n7bq23)

Surface tracker - marker exporter respect export range

---

pupil_src/shared_modules/pupil_detector_plugins/visualizer_2d.py

---
[ClickUp Task](https://app.clickup.com/t/nb80w2)

Fix pupil center circle size

---

pupil_src/shared_modules/time_sync.py
requirements.txt

Handles https://github.com/pupil-labs/pupil/issues/2174 gracefully

Require zeromq-pyre >= 0.3.4

---

pupil_src/shared_modules/pupil_detector_plugins/pye3d_plugin.py
requirements.txt

Changes refraction model serialization from pickle to msgpack - https://github.com/pupil-labs/pye3d-detector/pull/38

Update pye3d requirements to 0.3.0

---

pupil_src/shared_modules/blink_detection.py

Hate to be that guy...
There are some screenshots in the documentation that might need to be changed too.

Small typo fix, Activity in the UI

---

pupil_src/shared_modules/audio_playback.py
requirements.txt

https://python-sounddevice.readthedocs.io/en/0.4.4/ is a very well documented and maintained portaudio wrapper that works very similarly to the outdated `pyaudio` portaudio wrapper.

Use sounddevice instead of outdated pyaudio

---

pupil_src/launchables/player.py
pupil_src/shared_modules/plugin.py

Python files need to be placed in `player_settings/plugins/recording-upgrades/`

Allow modification of Player import process via user python files

---

README.md
pupil_src/launchables/player.py

Player: Run the recording upgrade such that it does not block the UI
